In [1]:
#Code for Data Mining and Cleaning of three data frames
#Code written by Zara Clacken

In [2]:
#Import Packages
import warnings
warnings.filterwarnings('ignore')  
import numpy as np
import pandas as pd

In [3]:
#Import Data Sets
educationraw = pd.read_csv('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Raw Data/Student Race and Ethnicity.csv')
singleparentkidsraw = pd.read_excel('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Raw Data/Children in single-parent families by race.xlsx')
povertyraw = pd.read_csv('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Raw Data/Poverty by Race and Ethnicity.csv')

---

---

In [4]:
#Clean and mine the data from the raw Student Race and Ethnicity Data Set 
educationraw

,ID IPEDS Race,IPEDS Race,ID Year,Year,Completions,Geography,ID Geography,Slug Geography,share
0,asian,Asian,2017,2017,298112,United States,01000US,united-states,0.061655
1,black,Black or African American,2017,2017,576612,United States,01000US,united-states,0.119254
2,hawaiian,Native Hawaiian or Other Pacific Islanders,2017,2017,14034,United States,01000US,united-states,0.002902
3,hispanic,Hispanic or Latino,2017,2017,786273,United States,01000US,united-states,0.162616
4,multiracial,Two or More Races,2017,2017,141479,United States,01000US,united-states,0.029260
5,native,American Indian or Alaska Native,2017,2017,33272,United States,01000US,united-states,0.006881
6,unknown,Unknown,2017,2017,220035,United States,01000US,united-states,0.045507
7,white,White,2017,2017,2765344,United States,01000US,united-states,0.571924
8,asian,Asian,2016,2016,284589,United States,01000US,united-states,0.059460
9,black,Black or African American,2016,2016,576255,United States,01000US,united-states,0.120399
10,hawaiian,Native Hawaiian or Other Pacific Islanders,2016,2016,13976,United States,01000US,united-states,0.002920
11,hispanic,Hispanic or Latino,2016,2016,740025,United States,01000US,united-states,0.154616
12,multiracial,Two or More Races,2016,2016,132024,United States,01000US,united-states,0.027584
13,native,American Indian or Alaska Native,2016,2016,33193,United States,01000US,united-states,0.006935
14,unknown,Unknown,2016,2016,238703,United States,01000US,united-states,0.049873
15,white,White,2016,2016,2767440,United States,01000US,united-states,0.578212
16,asian,Asian,2015,2015,273957,United States,01000US,united-states,0.057770
17,black,Black or African American,2015,2015,573638,United States,01000US,united-states,0.120964
18,hawaiian,Native Hawaiian or Other Pacific Islanders,2015,2015,14420,United States,01000US,united-states,0.003041
19,hispanic,Hispanic or Latino,2015,2015,687513,United States,01000US,united-states,0.144977
20,multiracial,Two or More Races,2015,2015,116276,United States,01000US,united-states,0.024519
21,native,American Indian or Alaska Native,2015,2015,33936,United States,01000US,united-states,0.007156
22,unknown,Unknown,2015,2015,252299,United States,01000US,united-states,0.053203
23,white,White,2015,2015,2790167,United States,01000US,united-states,0.588369
24,asian,Asian,2014,2014,264271,United States,01000US,united-states,0.056585
25,black,Black or African American,2014,2014,556705,United States,01000US,united-states,0.119201
26,hawaiian,Native Hawaiian or Other Pacific Islanders,2014,2014,14788,United States,01000US,united-states,0.003166
27,hispanic,Hispanic or Latino,2014,2014,638188,United States,01000US,united-states,0.136648
28,multiracial,Two or More Races,2014,2014,99685,United States,01000US,united-states,0.021344
29,native,American Indian or Alaska Native,2014,2014,34050,United States,01000US,united-states,0.007291
30,unknown,Unknown,2014,2014,270672,United States,01000US,united-states,0.057956
31,white,White,2014,2014,2791956,United States,01000US,united-states,0.597809
32,asian,Asian,2013,2013,257662,United States,01000US,united-states,0.056985
33,black,Black or African American,2013,2013,529285,United States,01000US,united-states,0.117059
34,hawaiian,Native Hawaiian or Other Pacific Islanders,2013,2013,14418,United States,01000US,united-states,0.003189
35,hispanic,Hispanic or Latino,2013,2013,589993,United States,01000US,united-states,0.130485
36,multiracial,Two or More Races,2013,2013,78724,United States,01000US,united-states,0.017411
37,native,American Indian or Alaska Native,2013,2013,34147,United States,01000US,united-states,0.007552
38,unknown,Unknown,2013,2013,263664,United States,01000US,united-states,0.058313
39,white,White,2013,2013,2753647,United States,01000US,united-states,0.609006
40,asian,Asian,2012,2012,248208,United States,01000US,united-states,0.055863
41,black,Black or African American,2012,2012,516275,United States,01000US,united-states,0.116195
42,hawaiian,Native Hawaiian or Other Pacific Islanders,2012,2012,13635,United States,01000US,united-states,0.003069
43,hispanic,Hispanic or Latino,2012,2012,550949,United States,01000US,united-states,0.123999
44,multiracial,Two or More Races,2012,2012,61313,United States,01000US,united-states,0.013799
45,native,American Indian or Alaska Native,2012,2012,33366,United States,01000US,united-states,0.007510
46,unknown,Unknown,2012,2012,291882,United States,01000US,united-states,0.065692
47,white,White,2012,2012,2727541,United States,01000US,united-states,0.613873

In [5]:
#Is the data for the entire nation?
educationraw.Geography.unique()

array(['United States'], dtype=object)

In [6]:
#Print out the Columns List
educationraw.columns

Index(['ID IPEDS Race', 'IPEDS Race', 'ID Year', 'Year', 'Completions',
       'Geography', 'ID Geography', 'Slug Geography', 'share'],
      dtype='object')

In [7]:
#Drop Undesired Columns
education = educationraw.drop(['ID IPEDS Race','ID Year',
       'Geography', 'ID Geography', 'Slug Geography'], axis =1)
education.head(6)

                                   IPEDS Race  Year  Completions     share
0                                       Asian  2017       298112  0.061655
1                   Black or African American  2017       576612  0.119254
2  Native Hawaiian or Other Pacific Islanders  2017        14034  0.002902
3                          Hispanic or Latino  2017       786273  0.162616
4                           Two or More Races  2017       141479  0.029260
5            American Indian or Alaska Native  2017        33272  0.006881

In [8]:
#Change column names
education.columns = ['Race', 'Year', 'DegreesCompleted', 'PercentofTotalDegrees']
education.head(6)

,Race,Year,DegreesCompleted,PercentofTotalDegrees
0,Asian,2017,298112,0.061655
1,Black or African American,2017,576612,0.119254
2,Native Hawaiian or Other Pacific Islanders,2017,14034,0.002902
3,Hispanic or Latino,2017,786273,0.162616
4,Two or More Races,2017,141479,0.029260
5,American Indian or Alaska Native,2017,33272,0.006881

In [9]:
#Multiply Total Degree Percentages by 100
education.PercentofTotalDegrees = (education.PercentofTotalDegrees)*100
education.head(6)

,Race,Year,DegreesCompleted,PercentofTotalDegrees
0,Asian,2017,298112,6.165503
1,Black or African American,2017,576612,11.925394
2,Native Hawaiian or Other Pacific Islanders,2017,14034,0.290249
3,Hispanic or Latino,2017,786273,16.261568
4,Two or More Races,2017,141479,2.926045
5,American Indian or Alaska Native,2017,33272,0.688126

In [10]:
#What are the unique races?
education.Race.unique().tolist()

['Asian',
 'Black or African American',
 'Native Hawaiian or Other Pacific Islanders',
 'Hispanic or Latino',
 'Two or More Races',
 'American Indian or Alaska Native',
 'Unknown',
 'White']

In [11]:
#Drop Rows where Race is Unknown 
index_Unknown = education[education.Race == 'Unknown'].index
education.drop(index_Unknown, inplace = True)
education.Race.unique().tolist()

['Asian',
 'Black or African American',
 'Native Hawaiian or Other Pacific Islanders',
 'Hispanic or Latino',
 'Two or More Races',
 'American Indian or Alaska Native',
 'White']

In [12]:
#Merge Asian plus Native Hawaiian or Other Pacific Islanders Degrees Completed into Asian and Pacific Islander Degrees Completed

In [13]:
#Sum Asian plus Native Hawaiian or Other Pacific Islanders Degrees Completed 
yearlist = education.Year.unique()
AADegrees = []
PIDegrees = []
for Y in yearlist:
    AADegrees.append(np.array(education[education.Year == Y][education.Race == 'Asian'].DegreesCompleted))
    PIDegrees.append(np.array(education[education.Year == Y][education.Race == 'Native Hawaiian or Other Pacific Islanders'].DegreesCompleted))
    AAPIDegrees = np.add(AADegrees,PIDegrees)
AAPIDegrees.tolist()

[[312146], [298565], [288377], [279059], [272080], [261843]]

In [14]:
#Sum Asian plus Native Hawaiian or Other Pacific Islanders Percents 
yearlist = education.Year.unique()
AAPercent = []
PIPercent = []
for Y in yearlist:
    AAPercent.append(np.array(education[education.Year == Y][education.Race == 'Asian'].PercentofTotalDegrees))
    PIPercent.append(np.array(education[education.Year == Y][education.Race == 'Native Hawaiian or Other Pacific Islanders'].PercentofTotalDegrees))
    AAPIPercent = np.add(AAPercent,PIPercent)
print(AAPIPercent.tolist(), end =' ')

[[6.4557519999999995], [6.238032], [6.0810728], [5.975164400000001], [6.0174189], [5.893158699999999]]

In [15]:
#Create an AAPI list to place into dictionary  

a = '"Asian and Pacific Islander"'
def AAPIfunc():
    counter = 0
    while counter < 6:
            print(counter,':', a , ',', end = ' ')
            counter = counter + 1 
AAPIfunc()

0 : "Asian and Pacific Islander" , 1 : "Asian and Pacific Islander" , 2 : "Asian and Pacific Islander" , 3 : "Asian and Pacific Islander" , 4 : "Asian and Pacific Islander" , 5 : "Asian and Pacific Islander" ,

In [16]:
# Dictionary for AAPI to enter into Race column
AAPIdict = {0 : "Asian and Pacific Islander" , 1 : "Asian and Pacific Islander" , 2 : "Asian and Pacific Islander" , 
            3 : "Asian and Pacific Islander" , 4 : "Asian and Pacific Islander" , 5 : "Asian and Pacific Islander"}

In [17]:
#Create a Year list to put into dictionary 
years = education.Year.unique().tolist()
def yearfunc():
    counter = 0
    while counter < 6: 
            for y in years:
                    print(counter, ':', y,',', end = ' ')
                    counter = counter +1 
yearfunc()

0 : 2017 , 1 : 2016 , 2 : 2015 , 3 : 2014 , 4 : 2013 , 5 : 2012 ,

In [18]:
#Dictionary for years
Yeardict = {0 : 2017 , 1 : 2016 , 2 : 2015 , 3 : 2014 , 4 : 2013 , 5 : 2012}

In [19]:
#List for Degrees Completed to put into dictionary
degrees = AAPIDegrees.tolist()
def degreefunc():
    counter = 0
    while counter < 6: 
            for d in degrees:
                    print(counter, ':', d,',', end = ' ')
                    counter = counter +1 
degreefunc()

0 : [312146] , 1 : [298565] , 2 : [288377] , 3 : [279059] , 4 : [272080] , 5 : [261843] ,

In [20]:
#Dictionary for degrees
Degreedict = {0 : 312146 , 1 : 298565 , 2 : 288377 , 3 : 279059 , 4 : 272080 , 5 : 261843}

In [21]:
#List for percentages
percentages = AAPIPercent.tolist()
def percentfunc():
    counter = 0
    while counter < 6: 
            for p in percentages:
                    print(counter, ':', p,',', end = ' ')
                    counter = counter +1 
percentfunc()

0 : [6.4557519999999995] , 1 : [6.238032] , 2 : [6.0810728] , 3 : [5.975164400000001] , 4 : [6.0174189] , 5 : [5.893158699999999] ,

In [22]:
#Create dictionary for percentages
Percentdict = {0 : 6.4557519999999995 , 1 : 6.238032 , 2 : 6.0810728 , 3 : 5.975164400000001 , 4 : 6.0174189 , 5 : 5.893158699999999}

In [23]:
#Test dictionaries
#AAPIdict[2]
#Yeardict[2]
#Degreedict[2]
#Percentdict[2]

In [24]:
education.columns

Index(['Race', 'Year', 'DegreesCompleted', 'PercentofTotalDegrees'], dtype='object')

In [25]:
#Insert New Rows for AAPI using Dictionaries 
numberlist = [0,1,2,3,4,5]
for n in numberlist:
    new_row = {'Race':AAPIdict[n], 'Year':Yeardict[n], 'DegreesCompleted':Degreedict[n],'PercentofTotalDegrees':Percentdict[n]}
    education = education.append(new_row, ignore_index=True)
education.tail(6)

                          Race  Year  DegreesCompleted  PercentofTotalDegrees
42  Asian and Pacific Islander  2017            312146               6.455752
43  Asian and Pacific Islander  2016            298565               6.238032
44  Asian and Pacific Islander  2015            288377               6.081073
45  Asian and Pacific Islander  2014            279059               5.975164
46  Asian and Pacific Islander  2013            272080               6.017419
47  Asian and Pacific Islander  2012            261843               5.893159

In [26]:
education.Race.unique()

array(['Asian', 'Black or African American',
       'Native Hawaiian or Other Pacific Islanders', 'Hispanic or Latino',
       'Two or More Races', 'American Indian or Alaska Native', 'White',
       'Asian and Pacific Islander'], dtype=object)

In [27]:
#Drop original Asian Rows and Native Hawaiian or Other Pacific Islanders rows
index_Asian = education[education.Race == 'Asian'].index
index_PacificHawaiin = education[education.Race == 'Native Hawaiian or Other Pacific Islanders'].index  
education.drop(index_Asian, inplace = True)
education.drop(index_PacificHawaiin, inplace = True)

#Check to see if the above races have been dropped
education.Race.unique()

array(['Black or African American', 'Hispanic or Latino',
       'Two or More Races', 'American Indian or Alaska Native', 'White',
       'Asian and Pacific Islander'], dtype=object)

In [28]:
#Change the names of the other races 
education.Race = education.Race.replace ('Black or African American','Black')

In [29]:
originalracelist = ['Black or African American','Hispanic or Latino','Two or More Races',
                    'American Indian or Alaska Native', 'White','Asian and Pacific Islander'] 
newracelist = ['Black','Hispanic','Multiracial','Native American','White','Asian and Pacific Islander']

In [30]:
#original race list function to put into dictionary
def ogracefunc():
    counter = 0
    while counter < 6: 
            for o in originalracelist:
                    print(counter, ':', o,',', end = ' ')
                    counter = counter +1 
ogracefunc()

0 : Black or African American , 1 : Hispanic or Latino , 2 : Two or More Races , 3 : American Indian or Alaska Native , 4 : White , 5 : Asian and Pacific Islander ,

In [31]:
#new race list function to put into dictionary 
def newracefunc():
    counter = 0
    while counter < 6: 
            for r in newracelist:
                    print(counter, ':', r,',', end = ' ')
                    counter = counter +1 
newracefunc()

0 : Black , 1 : Hispanic , 2 : Multiracial , 3 : Native American , 4 : White , 5 : Asian and Pacific Islander ,

In [32]:
#Use Dictionaries and a for loop to replace the original race names with new ones 
ogracedict = {0 : 'Black or African American' , 1 : 'Hispanic or Latino' , 2 : 'Two or More Races' , 3 : 'American Indian or Alaska Native' , 
              4 : 'White' , 5 : 'Asian and Pacific Islander' }
newracedict ={0 : 'Black' , 1 : 'Hispanic' , 2 : 'Multiracial' , 3 : 'Native American' , 4 : 'White' , 5 : 'Asian and Pacific Islander'}
for n in numberlist:
    education.Race = education.Race.replace(ogracedict[n], newracedict[n])
education.Race.unique()

array(['Black', 'Hispanic', 'Multiracial', 'Native American', 'White',
       'Asian and Pacific Islander'], dtype=object)

In [33]:
#Round Percent of Total Degrees Column
education.PercentofTotalDegrees = np.round(education.PercentofTotalDegrees,2)
education.head(6)

              Race  Year  DegreesCompleted  PercentofTotalDegrees
1            Black  2017            576612                  11.93
3         Hispanic  2017            786273                  16.26
4      Multiracial  2017            141479                   2.93
5  Native American  2017             33272                   0.69
6            White  2017           2765344                  57.19
8            Black  2016            576255                  12.04

In [34]:
#Final data frame
education

                          Race  Year  DegreesCompleted  PercentofTotalDegrees
1                        Black  2017            576612                  11.93
3                     Hispanic  2017            786273                  16.26
4                  Multiracial  2017            141479                   2.93
5              Native American  2017             33272                   0.69
6                        White  2017           2765344                  57.19
8                        Black  2016            576255                  12.04
10                    Hispanic  2016            740025                  15.46
11                 Multiracial  2016            132024                   2.76
12             Native American  2016             33193                   0.69
13                       White  2016           2767440                  57.82
15                       Black  2015            573638                  12.10
17                    Hispanic  2015            687513                  14.50
18                 Multiracial  2015            116276                   2.45
19             Native American  2015             33936                   0.72
20                       White  2015           2790167                  58.84
22                       Black  2014            556705                  11.92
24                    Hispanic  2014            638188                  13.66
25                 Multiracial  2014             99685                   2.13
26             Native American  2014             34050                   0.73
27                       White  2014           2791956                  59.78
29                       Black  2013            529285                  11.71
31                    Hispanic  2013            589993                  13.05
32                 Multiracial  2013             78724                   1.74
33             Native American  2013             34147                   0.76
34                       White  2013           2753647                  60.90
36                       Black  2012            516275                  11.62
38                    Hispanic  2012            550949                  12.40
39                 Multiracial  2012             61313                   1.38
40             Native American  2012             33366                   0.75
41                       White  2012           2727541                  61.39
42  Asian and Pacific Islander  2017            312146                   6.46
43  Asian and Pacific Islander  2016            298565                   6.24
44  Asian and Pacific Islander  2015            288377                   6.08
45  Asian and Pacific Islander  2014            279059                   5.98
46  Asian and Pacific Islander  2013            272080                   6.02
47  Asian and Pacific Islander  2012            261843                   5.89

---

---

In [35]:
#Clean and mine the data for Single-Parent Families by Race Data Frame

In [36]:
singleparentkidsraw

,LocationType,Location,Race,TimeFrame,DataFormat,Data
0,Nation,United States,American Indian,2005,Percent,0.49
1,Nation,United States,Asian and Pacific Islander,2005,Percent,0.17
2,Nation,United States,Black or African American,2005,Percent,0.65
3,Nation,United States,Hispanic or Latino,2005,Percent,0.36
4,Nation,United States,Non-Hispanic White,2005,Percent,0.23
...,...,...,...,...,...,...
11077,Territory,Puerto Rico,Non-Hispanic White,2019,Number,S
11078,Territory,Puerto Rico,Hispanic or Latino,2019,Number,341000
11079,Territory,Puerto Rico,Black or African American,2019,Number,44000
11080,Territory,Puerto Rico,Asian and Pacific Islander,2019,Number,S
11081,Territory,Puerto Rico,American Indian,2019,Number,S

In [37]:
#Column Names?
singleparentkidsraw.columns

Index(['LocationType', 'Location', 'Race', 'TimeFrame', 'DataFormat', 'Data'], dtype='object')

In [38]:
#Number of Rows?
len(singleparentkidsraw)

11082

In [39]:
#Change Column Names
singleparentkidsraw.columns = ['LocationType', 'Location', 'Race', 'Year', 'DataFormat', 'TotalChildren']
singleparentkidsraw.columns

Index(['LocationType', 'Location', 'Race', 'Year', 'DataFormat',
       'TotalChildren'],
      dtype='object')

In [40]:
#What are the Unique Values of each Column?
singleparentkidsraw.LocationType.unique()

array(['Nation', 'State', 'City', 'Territory'], dtype=object)

In [41]:
singleparentkidsraw.DataFormat.unique()

array(['Percent', 'Number'], dtype=object)

In [42]:
singleparentkidsraw.Race.unique()

array(['American Indian', 'Asian and Pacific Islander',
       'Black or African American', 'Hispanic or Latino',
       'Non-Hispanic White', 'Two or more races', 'Total'], dtype=object)

In [43]:
singleparentkidsraw.Year.unique()

array([2005, 2006, 2007, 2008, 2013, 2018, 2009, 2010, 2015, 2011, 2012,
       2014, 2016, 2017, 2019], dtype=int64)

In [44]:
#Drop LocationType, Location, DataFormat, and Data Columns
#Filter Data Set to show the years 2010-2019 

YearFilter1 = singleparentkidsraw.Year > 2009  
YearFilter2 = singleparentkidsraw.Year < 2020
FormatFilter = singleparentkidsraw.DataFormat == 'Number'
LocationFilter = singleparentkidsraw.LocationType == 'Nation'
TotalFilter = singleparentkidsraw.Race != 'Total'

singleparentkids = singleparentkidsraw[YearFilter1][YearFilter2][FormatFilter][LocationFilter][TotalFilter].drop(['LocationType','Location','DataFormat'], axis = 1)

singleparentkids.tail(11)

                           Race  Year TotalChildren
184          Non-Hispanic White  2017       8623000
185          Hispanic or Latino  2017       7283000
186   Black or African American  2017       6123000
187  Asian and Pacific Islander  2017        556000
188             American Indian  2017        351000
203          Non-Hispanic White  2019       8479000
204          Hispanic or Latino  2019       7339000
205   Black or African American  2019       5988000
206  Asian and Pacific Islander  2019        549000
208           Two or more races  2019       1923000
209             American Indian  2019        341000

In [45]:
#Race Values?
singleparentkids.Race.unique()

array(['American Indian', 'Asian and Pacific Islander',
       'Black or African American', 'Hispanic or Latino',
       'Non-Hispanic White', 'Two or more races'], dtype=object)

In [46]:
#Year Values the Same?
singleparentkids.Year.unique()

array([2013, 2018, 2010, 2011, 2015, 2012, 2014, 2016, 2017, 2019],
      dtype=int64)

In [47]:
#How many rows in data frame now?
len(singleparentkids)

60

In [48]:
#Check Variable Data Types
singleparentkids.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 63 to 209
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Race           60 non-null     object
 1   Year           60 non-null     int64
 2   TotalChildren  60 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.9+ KB

In [49]:
#Change Variable Data Types
singleparentkids.Year = singleparentkids.Year.astype('category')
singleparentkids.Race = singleparentkids.Race.astype('category')
singleparentkids.TotalChildren = singleparentkids.TotalChildren.astype('int64')

In [50]:
#Check Data Type Changes
singleparentkids.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 63 to 209
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Race           60 non-null     category
 1   Year           60 non-null     category
 2   TotalChildren  60 non-null     int64
dtypes: category(2), int64(1)
memory usage: 1.6 KB

In [51]:
singleparentkids.head(6)

                          Race  Year  TotalChildren
63             American Indian  2013         329000
64  Asian and Pacific Islander  2013         557000
65   Black or African American  2013        6427000
66          Hispanic or Latino  2013        7044000
67          Non-Hispanic White  2013        9289000
68           Two or more races  2013        1758000

In [52]:
singleparentkids.Race.unique()

[American Indian, Asian and Pacific Islander, Black or African American, Hispanic or Latino, Non-Hispanic White, Two or more races]
Categories (6, object): [American Indian, Asian and Pacific Islander, Black or African American, Hispanic or Latino, Non-Hispanic White, Two or more races]

In [53]:
singleparentkids.Year.unique()

[2013, 2018, 2010, 2011, 2015, 2012, 2014, 2016, 2017, 2019]
Categories (10, int64): [2013, 2018, 2010, 2011, ..., 2014, 2016, 2017, 2019]

In [54]:
#Percentage Each Race is of Total Single Parent Children

In [55]:
#Total Number of Children of All Races Per Year

yearlist = [2013, 2018, 2010, 2011, 2015, 2012, 2014, 2016, 2017, 2019]

for Y in yearlist:
    S = singleparentkids[singleparentkids.Year == Y].TotalChildren.sum()
    print(Y,':',S, ',', end =' ')

2013 : 25404000 , 2018 : 24832000 , 2010 : 25011000 , 2011 : 25434000 , 2015 : 25216000 , 2012 : 25486000 , 2014 : 25469000 , 2016 : 25088000 , 2017 : 24823000 , 2019 : 24619000 ,

In [56]:
#Create a Dictionary For the Sums 
Sums = {2013 : 25404000 , 2018 : 24832000 , 2010 : 25011000 , 2011 : 25434000 , 2015 : 25216000 , 2012 : 25486000 , 2014 : 25469000 ,
        2016 : 25088000 , 2017 : 24823000 , 2019 : 24619000} 
Sums[2015]

25216000

In [57]:
#Create New Column for Percentage of a Year's Total Population 
singleparentkids['PercentofTotalPopulation'] = " "
singleparentkids

                           Race  Year  TotalChildren PercentofTotalPopulation
63              American Indian  2013         329000
64   Asian and Pacific Islander  2013         557000
65    Black or African American  2013        6427000
66           Hispanic or Latino  2013        7044000
67           Non-Hispanic White  2013        9289000
68            Two or more races  2013        1758000
71            Two or more races  2018        1944000
72           Non-Hispanic White  2018        8526000
73           Hispanic or Latino  2018        7301000
74    Black or African American  2018        6166000
75   Asian and Pacific Islander  2018         547000
76              American Indian  2018         348000
98              American Indian  2010         350000
99   Asian and Pacific Islander  2010         539000
100   Black or African American  2010        6533000
101          Hispanic or Latino  2010        6674000
102          Non-Hispanic White  2010        9329000
103           Two or more races  2010        1586000
119             American Indian  2011         355000
120  Asian and Pacific Islander  2011         559000
121   Black or African American  2011        6509000
122          Hispanic or Latino  2011        6890000
123          Non-Hispanic White  2011        9466000
124           Two or more races  2011        1655000
127           Two or more races  2015        1804000
128          Non-Hispanic White  2015        8998000
129          Hispanic or Latino  2015        7180000
130   Black or African American  2015        6333000
131  Asian and Pacific Islander  2015         568000
132             American Indian  2015         333000
147             American Indian  2012         345000
148  Asian and Pacific Islander  2012         579000
149   Black or African American  2012        6493000
150          Hispanic or Latino  2012        7008000
151          Non-Hispanic White  2012        9358000
152           Two or more races  2012        1703000
154             American Indian  2014         341000
155  Asian and Pacific Islander  2014         578000
156   Black or African American  2014        6382000
157          Hispanic or Latino  2014        7190000
158          Non-Hispanic White  2014        9181000
159           Two or more races  2014        1797000
176           Two or more races  2016        1900000
177          Non-Hispanic White  2016        8766000
178          Hispanic or Latino  2016        7230000
179   Black or African American  2016        6281000
180  Asian and Pacific Islander  2016         572000
181             American Indian  2016         339000
183           Two or more races  2017        1887000
184          Non-Hispanic White  2017        8623000
185          Hispanic or Latino  2017        7283000
186   Black or African American  2017        6123000
187  Asian and Pacific Islander  2017         556000
188             American Indian  2017         351000
203          Non-Hispanic White  2019        8479000
204          Hispanic or Latino  2019        7339000
205   Black or African American  2019        5988000
206  Asian and Pacific Islander  2019         549000
208           Two or more races  2019        1923000
209             American Indian  2019         341000

In [58]:
len(singleparentkids)

60

In [59]:
#Create a function, using the dictionary, to calculate percentages 
import numpy as np
percentages = []
for Y in yearlist:
    percentages.append(np.round(100*(singleparentkids[singleparentkids.Year == Y].TotalChildren/Sums[Y]),2))
P = np.array(percentages).reshape(60,1)
P

array([[ 1.3 ],
       [ 2.19],
       [25.3 ],
       [27.73],
       [36.57],
       [ 6.92],
       [ 7.83],
       [34.33],
       [29.4 ],
       [24.83],
       [ 2.2 ],
       [ 1.4 ],
       [ 1.4 ],
       [ 2.16],
       [26.12],
       [26.68],
       [37.3 ],
       [ 6.34],
       [ 1.4 ],
       [ 2.2 ],
       [25.59],
       [27.09],
       [37.22],
       [ 6.51],
       [ 7.15],
       [35.68],
       [28.47],
       [25.12],
       [ 2.25],
       [ 1.32],
       [ 1.35],
       [ 2.27],
       [25.48],
       [27.5 ],
       [36.72],
       [ 6.68],
       [ 1.34],
       [ 2.27],
       [25.06],
       [28.23],
       [36.05],
       [ 7.06],
       [ 7.57],
       [34.94],
       [28.82],
       [25.04],
       [ 2.28],
       [ 1.35],
       [ 7.6 ],
       [34.74],
       [29.34],
       [24.67],
       [ 2.24],
       [ 1.41],
       [34.44],
       [29.81],
       [24.32],
       [ 2.23],
       [ 7.81],
       [ 1.39]])

In [60]:
#Insert Percent Column into Data Frame
singleparentkids['PercentofTotalPopulation'] = P 
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              American Indian  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65    Black or African American  2013        6427000                     25.30
66           Hispanic or Latino  2013        7044000                     27.73
67           Non-Hispanic White  2013        9289000                     36.57
68            Two or more races  2013        1758000                      6.92
71            Two or more races  2018        1944000                      7.83
72           Non-Hispanic White  2018        8526000                     34.33
73           Hispanic or Latino  2018        7301000                     29.40
74    Black or African American  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              American Indian  2018         348000                      1.40
98              American Indian  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100   Black or African American  2010        6533000                     26.12
101          Hispanic or Latino  2010        6674000                     26.68
102          Non-Hispanic White  2010        9329000                     37.30
103           Two or more races  2010        1586000                      6.34
119             American Indian  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121   Black or African American  2011        6509000                     25.59
122          Hispanic or Latino  2011        6890000                     27.09
123          Non-Hispanic White  2011        9466000                     37.22
124           Two or more races  2011        1655000                      6.51
127           Two or more races  2015        1804000                      7.15
128          Non-Hispanic White  2015        8998000                     35.68
129          Hispanic or Latino  2015        7180000                     28.47
130   Black or African American  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             American Indian  2015         333000                      1.32
147             American Indian  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149   Black or African American  2012        6493000                     25.48
150          Hispanic or Latino  2012        7008000                     27.50
151          Non-Hispanic White  2012        9358000                     36.72
152           Two or more races  2012        1703000                      6.68
154             American Indian  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156   Black or African American  2014        6382000                     25.06
157          Hispanic or Latino  2014        7190000                     28.23
158          Non-Hispanic White  2014        9181000                     36.05
159           Two or more races  2014        1797000                      7.06
176           Two or more races  2016        1900000                      7.57
177          Non-Hispanic White  2016        8766000                     34.94
178          Hispanic or Latino  2016        7230000                     28.82
179   Black or African American  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             American Indian  2016         339000                      1.35
183           Two or more races  2017        1887000                      7.60
184          Non-Hispanic White  2017        8623000                     34.74
185          Hispanic or Latino  2017        7283000                     29.34
186   Black or African American  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             American Indian  2017         351000                      1.41
203          Non-Hispanic White  2019        8479000                     34.44
204          Hispanic or Latino  2019        7339000                     29.81
205   Black or African American  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208           Two or more races  2019        1923000                      7.81
209             American Indian  2019         341000                      1.39

In [61]:
#Unique Races
singleparentkids.Race.unique().tolist()

['American Indian',
 'Asian and Pacific Islander',
 'Black or African American',
 'Hispanic or Latino',
 'Non-Hispanic White',
 'Two or more races']

In [62]:
#Replace American Indian with Native American 
singleparentkids.Race = singleparentkids.Race.replace('American Indian','Native American')
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              Native American  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65    Black or African American  2013        6427000                     25.30
66           Hispanic or Latino  2013        7044000                     27.73
67           Non-Hispanic White  2013        9289000                     36.57
68            Two or more races  2013        1758000                      6.92
71            Two or more races  2018        1944000                      7.83
72           Non-Hispanic White  2018        8526000                     34.33
73           Hispanic or Latino  2018        7301000                     29.40
74    Black or African American  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              Native American  2018         348000                      1.40
98              Native American  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100   Black or African American  2010        6533000                     26.12
101          Hispanic or Latino  2010        6674000                     26.68
102          Non-Hispanic White  2010        9329000                     37.30
103           Two or more races  2010        1586000                      6.34
119             Native American  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121   Black or African American  2011        6509000                     25.59
122          Hispanic or Latino  2011        6890000                     27.09
123          Non-Hispanic White  2011        9466000                     37.22
124           Two or more races  2011        1655000                      6.51
127           Two or more races  2015        1804000                      7.15
128          Non-Hispanic White  2015        8998000                     35.68
129          Hispanic or Latino  2015        7180000                     28.47
130   Black or African American  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             Native American  2015         333000                      1.32
147             Native American  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149   Black or African American  2012        6493000                     25.48
150          Hispanic or Latino  2012        7008000                     27.50
151          Non-Hispanic White  2012        9358000                     36.72
152           Two or more races  2012        1703000                      6.68
154             Native American  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156   Black or African American  2014        6382000                     25.06
157          Hispanic or Latino  2014        7190000                     28.23
158          Non-Hispanic White  2014        9181000                     36.05
159           Two or more races  2014        1797000                      7.06
176           Two or more races  2016        1900000                      7.57
177          Non-Hispanic White  2016        8766000                     34.94
178          Hispanic or Latino  2016        7230000                     28.82
179   Black or African American  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             Native American  2016         339000                      1.35
183           Two or more races  2017        1887000                      7.60
184          Non-Hispanic White  2017        8623000                     34.74
185          Hispanic or Latino  2017        7283000                     29.34
186   Black or African American  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             Native American  2017         351000                      1.41
203          Non-Hispanic White  2019        8479000                     34.44
204          Hispanic or Latino  2019        7339000                     29.81
205   Black or African American  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208           Two or more races  2019        1923000                      7.81
209             Native American  2019         341000                      1.39

In [63]:
#Replace Non-Hispanic White with White
singleparentkids.Race = singleparentkids.Race.replace ('Non-Hispanic White','White')
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              Native American  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65    Black or African American  2013        6427000                     25.30
66           Hispanic or Latino  2013        7044000                     27.73
67                        White  2013        9289000                     36.57
68            Two or more races  2013        1758000                      6.92
71            Two or more races  2018        1944000                      7.83
72                        White  2018        8526000                     34.33
73           Hispanic or Latino  2018        7301000                     29.40
74    Black or African American  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              Native American  2018         348000                      1.40
98              Native American  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100   Black or African American  2010        6533000                     26.12
101          Hispanic or Latino  2010        6674000                     26.68
102                       White  2010        9329000                     37.30
103           Two or more races  2010        1586000                      6.34
119             Native American  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121   Black or African American  2011        6509000                     25.59
122          Hispanic or Latino  2011        6890000                     27.09
123                       White  2011        9466000                     37.22
124           Two or more races  2011        1655000                      6.51
127           Two or more races  2015        1804000                      7.15
128                       White  2015        8998000                     35.68
129          Hispanic or Latino  2015        7180000                     28.47
130   Black or African American  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             Native American  2015         333000                      1.32
147             Native American  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149   Black or African American  2012        6493000                     25.48
150          Hispanic or Latino  2012        7008000                     27.50
151                       White  2012        9358000                     36.72
152           Two or more races  2012        1703000                      6.68
154             Native American  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156   Black or African American  2014        6382000                     25.06
157          Hispanic or Latino  2014        7190000                     28.23
158                       White  2014        9181000                     36.05
159           Two or more races  2014        1797000                      7.06
176           Two or more races  2016        1900000                      7.57
177                       White  2016        8766000                     34.94
178          Hispanic or Latino  2016        7230000                     28.82
179   Black or African American  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             Native American  2016         339000                      1.35
183           Two or more races  2017        1887000                      7.60
184                       White  2017        8623000                     34.74
185          Hispanic or Latino  2017        7283000                     29.34
186   Black or African American  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             Native American  2017         351000                      1.41
203                       White  2019        8479000                     34.44
204          Hispanic or Latino  2019        7339000                     29.81
205   Black or African American  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208           Two or more races  2019        1923000                      7.81
209             Native American  2019         341000                      1.39

In [64]:
#Replace Two or more races with Multiracial
singleparentkids.Race = singleparentkids.Race.replace ('Two or more races','Multiracial')
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              Native American  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65    Black or African American  2013        6427000                     25.30
66           Hispanic or Latino  2013        7044000                     27.73
67                        White  2013        9289000                     36.57
68                  Multiracial  2013        1758000                      6.92
71                  Multiracial  2018        1944000                      7.83
72                        White  2018        8526000                     34.33
73           Hispanic or Latino  2018        7301000                     29.40
74    Black or African American  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              Native American  2018         348000                      1.40
98              Native American  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100   Black or African American  2010        6533000                     26.12
101          Hispanic or Latino  2010        6674000                     26.68
102                       White  2010        9329000                     37.30
103                 Multiracial  2010        1586000                      6.34
119             Native American  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121   Black or African American  2011        6509000                     25.59
122          Hispanic or Latino  2011        6890000                     27.09
123                       White  2011        9466000                     37.22
124                 Multiracial  2011        1655000                      6.51
127                 Multiracial  2015        1804000                      7.15
128                       White  2015        8998000                     35.68
129          Hispanic or Latino  2015        7180000                     28.47
130   Black or African American  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             Native American  2015         333000                      1.32
147             Native American  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149   Black or African American  2012        6493000                     25.48
150          Hispanic or Latino  2012        7008000                     27.50
151                       White  2012        9358000                     36.72
152                 Multiracial  2012        1703000                      6.68
154             Native American  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156   Black or African American  2014        6382000                     25.06
157          Hispanic or Latino  2014        7190000                     28.23
158                       White  2014        9181000                     36.05
159                 Multiracial  2014        1797000                      7.06
176                 Multiracial  2016        1900000                      7.57
177                       White  2016        8766000                     34.94
178          Hispanic or Latino  2016        7230000                     28.82
179   Black or African American  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             Native American  2016         339000                      1.35
183                 Multiracial  2017        1887000                      7.60
184                       White  2017        8623000                     34.74
185          Hispanic or Latino  2017        7283000                     29.34
186   Black or African American  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             Native American  2017         351000                      1.41
203                       White  2019        8479000                     34.44
204          Hispanic or Latino  2019        7339000                     29.81
205   Black or African American  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208                 Multiracial  2019        1923000                      7.81
209             Native American  2019         341000                      1.39

In [65]:
#Replace Hispanic or Latino with Hispanic
singleparentkids.Race = singleparentkids.Race.replace ('Hispanic or Latino','Hispanic')
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              Native American  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65    Black or African American  2013        6427000                     25.30
66                     Hispanic  2013        7044000                     27.73
67                        White  2013        9289000                     36.57
68                  Multiracial  2013        1758000                      6.92
71                  Multiracial  2018        1944000                      7.83
72                        White  2018        8526000                     34.33
73                     Hispanic  2018        7301000                     29.40
74    Black or African American  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              Native American  2018         348000                      1.40
98              Native American  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100   Black or African American  2010        6533000                     26.12
101                    Hispanic  2010        6674000                     26.68
102                       White  2010        9329000                     37.30
103                 Multiracial  2010        1586000                      6.34
119             Native American  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121   Black or African American  2011        6509000                     25.59
122                    Hispanic  2011        6890000                     27.09
123                       White  2011        9466000                     37.22
124                 Multiracial  2011        1655000                      6.51
127                 Multiracial  2015        1804000                      7.15
128                       White  2015        8998000                     35.68
129                    Hispanic  2015        7180000                     28.47
130   Black or African American  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             Native American  2015         333000                      1.32
147             Native American  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149   Black or African American  2012        6493000                     25.48
150                    Hispanic  2012        7008000                     27.50
151                       White  2012        9358000                     36.72
152                 Multiracial  2012        1703000                      6.68
154             Native American  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156   Black or African American  2014        6382000                     25.06
157                    Hispanic  2014        7190000                     28.23
158                       White  2014        9181000                     36.05
159                 Multiracial  2014        1797000                      7.06
176                 Multiracial  2016        1900000                      7.57
177                       White  2016        8766000                     34.94
178                    Hispanic  2016        7230000                     28.82
179   Black or African American  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             Native American  2016         339000                      1.35
183                 Multiracial  2017        1887000                      7.60
184                       White  2017        8623000                     34.74
185                    Hispanic  2017        7283000                     29.34
186   Black or African American  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             Native American  2017         351000                      1.41
203                       White  2019        8479000                     34.44
204                    Hispanic  2019        7339000                     29.81
205   Black or African American  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208                 Multiracial  2019        1923000                      7.81
209             Native American  2019         341000                      1.39

In [66]:
#Replace Black or African-American with Black
singleparentkids.Race = singleparentkids.Race.replace ('Black or African American','Black')
singleparentkids

                           Race  Year  TotalChildren  PercentofTotalPopulation
63              Native American  2013         329000                      1.30
64   Asian and Pacific Islander  2013         557000                      2.19
65                        Black  2013        6427000                     25.30
66                     Hispanic  2013        7044000                     27.73
67                        White  2013        9289000                     36.57
68                  Multiracial  2013        1758000                      6.92
71                  Multiracial  2018        1944000                      7.83
72                        White  2018        8526000                     34.33
73                     Hispanic  2018        7301000                     29.40
74                        Black  2018        6166000                     24.83
75   Asian and Pacific Islander  2018         547000                      2.20
76              Native American  2018         348000                      1.40
98              Native American  2010         350000                      1.40
99   Asian and Pacific Islander  2010         539000                      2.16
100                       Black  2010        6533000                     26.12
101                    Hispanic  2010        6674000                     26.68
102                       White  2010        9329000                     37.30
103                 Multiracial  2010        1586000                      6.34
119             Native American  2011         355000                      1.40
120  Asian and Pacific Islander  2011         559000                      2.20
121                       Black  2011        6509000                     25.59
122                    Hispanic  2011        6890000                     27.09
123                       White  2011        9466000                     37.22
124                 Multiracial  2011        1655000                      6.51
127                 Multiracial  2015        1804000                      7.15
128                       White  2015        8998000                     35.68
129                    Hispanic  2015        7180000                     28.47
130                       Black  2015        6333000                     25.12
131  Asian and Pacific Islander  2015         568000                      2.25
132             Native American  2015         333000                      1.32
147             Native American  2012         345000                      1.35
148  Asian and Pacific Islander  2012         579000                      2.27
149                       Black  2012        6493000                     25.48
150                    Hispanic  2012        7008000                     27.50
151                       White  2012        9358000                     36.72
152                 Multiracial  2012        1703000                      6.68
154             Native American  2014         341000                      1.34
155  Asian and Pacific Islander  2014         578000                      2.27
156                       Black  2014        6382000                     25.06
157                    Hispanic  2014        7190000                     28.23
158                       White  2014        9181000                     36.05
159                 Multiracial  2014        1797000                      7.06
176                 Multiracial  2016        1900000                      7.57
177                       White  2016        8766000                     34.94
178                    Hispanic  2016        7230000                     28.82
179                       Black  2016        6281000                     25.04
180  Asian and Pacific Islander  2016         572000                      2.28
181             Native American  2016         339000                      1.35
183                 Multiracial  2017        1887000                      7.60
184                       White  2017        8623000                     34.74
185                    Hispanic  2017        7283000                     29.34
186                       Black  2017        6123000                     24.67
187  Asian and Pacific Islander  2017         556000                      2.24
188             Native American  2017         351000                      1.41
203                       White  2019        8479000                     34.44
204                    Hispanic  2019        7339000                     29.81
205                       Black  2019        5988000                     24.32
206  Asian and Pacific Islander  2019         549000                      2.23
208                 Multiracial  2019        1923000                      7.81
209             Native American  2019         341000                      1.39

In [67]:
singleparentkids.columns

Index(['Race', 'Year', 'TotalChildren', 'PercentofTotalPopulation'], dtype='object')

In [68]:
#Change Column Names Again For Export to be joined with other dataframes in SQL
singleparentkids.columns = ['Race', 'Year', 'Number of Children(Single Parent Homes)', 'Percent of Total Children(Single Parent Homes)']

In [69]:
sorted(singleparentkids.Year.unique().tolist())

[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [70]:
#Drop Years outside of 2013-2017 
dropyearlist = [2010, 2011, 2012, 2018, 2019]
for y in dropyearlist:
    index_years = singleparentkids[singleparentkids.Year == y].index
    singleparentkids.drop(index_years, inplace = True)
sorted(singleparentkids.Year.unique().tolist())

[2013, 2014, 2015, 2016, 2017]

In [71]:
#Final Data Frame
singleparentkids

,Race,Year,Number of Children(Single Parent Homes),Percent of Total Children(Single Parent Homes)
63,Native American,2013,329000,1.30
64,Asian and Pacific Islander,2013,557000,2.19
65,Black,2013,6427000,25.30
66,Hispanic,2013,7044000,27.73
67,White,2013,9289000,36.57
68,Multiracial,2013,1758000,6.92
127,Multiracial,2015,1804000,7.15
128,White,2015,8998000,35.68
129,Hispanic,2015,7180000,28.47
130,Black,2015,6333000,25.12
131,Asian and Pacific Islander,2015,568000,2.25
132,Native American,2015,333000,1.32
154,Native American,2014,341000,1.34
155,Asian and Pacific Islander,2014,578000,2.27
156,Black,2014,6382000,25.06
157,Hispanic,2014,7190000,28.23
158,White,2014,9181000,36.05
159,Multiracial,2014,1797000,7.06
176,Multiracial,2016,1900000,7.57
177,White,2016,8766000,34.94
178,Hispanic,2016,7230000,28.82
179,Black,2016,6281000,25.04
180,Asian and Pacific Islander,2016,572000,2.28
181,Native American,2016,339000,1.35
183,Multiracial,2017,1887000,7.60
184,White,2017,8623000,34.74
185,Hispanic,2017,7283000,29.34
186,Black,2017,6123000,24.67
187,Asian and Pacific Islander,2017,556000,2.24
188,Native American,2017,351000,1.41

---

---

In [72]:
#Clean Poverty by Race and Ethnicity data frame

In [73]:
povertyraw

,ID Race,Race,ID Year,Year,ID Poverty Status,Poverty Status,Poverty Population,Poverty Population Margin of Error(Moe),Geography,ID Geography,Slug Geography,share
0,1,White,2013,2013,0,Income In The Past 12 Months Below Poverty Level,29701062,97115.895530,United States,01000US,united-states,0.479823
1,1,White,2014,2014,0,Income In The Past 12 Months Below Poverty Level,29193983,92676.176460,United States,01000US,united-states,0.476341
2,1,White,2015,2015,0,Income In The Past 12 Months Below Poverty Level,28027149,95135.243000,United States,01000US,united-states,0.477800
3,1,White,2016,2016,0,Income In The Past 12 Months Below Poverty Level,26653418,92998.998830,United States,01000US,united-states,0.475246
4,1,White,2017,2017,0,Income In The Past 12 Months Below Poverty Level,25668489,89754.419970,United States,01000US,united-states,0.477490
5,1,White,2018,2018,0,Income In The Past 12 Months Below Poverty Level,25230693,90255.224380,United States,01000US,united-states,0.477151
6,9,Hispanic,2013,2013,0,Income In The Past 12 Months Below Poverty Level,13089210,60768.446300,United States,01000US,united-states,0.211457
7,9,Hispanic,2014,2014,0,Income In The Past 12 Months Below Poverty Level,13079584,60525.658200,United States,01000US,united-states,0.213412
8,9,Hispanic,2015,2015,0,Income In The Past 12 Months Below Poverty Level,12505613,63334.284890,United States,01000US,united-states,0.213193
9,9,Hispanic,2016,2016,0,Income In The Past 12 Months Below Poverty Level,11814468,61008.833560,United States,01000US,united-states,0.210659
10,9,Hispanic,2017,2017,0,Income In The Past 12 Months Below Poverty Level,11173521,60557.196800,United States,01000US,united-states,0.207852
11,9,Hispanic,2018,2018,0,Income In The Past 12 Months Below Poverty Level,11025445,64930.124110,United States,01000US,united-states,0.208508
12,2,Black,2013,2013,0,Income In The Past 12 Months Below Poverty Level,10538290,54162.147670,United States,01000US,united-states,0.170247
13,2,Black,2014,2014,0,Income In The Past 12 Months Below Poverty Level,10434389,55886.169110,United States,01000US,united-states,0.170252
14,2,Black,2015,2015,0,Income In The Past 12 Months Below Poverty Level,9905872,55994.616540,United States,01000US,united-states,0.168873
15,2,Black,2016,2016,0,Income In The Past 12 Months Below Poverty Level,9366792,55843.164860,United States,01000US,united-states,0.167015
16,2,Black,2017,2017,0,Income In The Past 12 Months Below Poverty Level,9122033,58930.514780,United States,01000US,united-states,0.169690
17,2,Black,2018,2018,0,Income In The Past 12 Months Below Poverty Level,8971239,58040.756140,United States,01000US,united-states,0.169660
18,6,Other,2013,2013,0,Income In The Past 12 Months Below Poverty Level,3913285,37953.370760,United States,01000US,united-states,0.063219
19,6,Other,2014,2014,0,Income In The Past 12 Months Below Poverty Level,3852708,34912.027150,United States,01000US,united-states,0.062862
20,6,Other,2016,2016,0,Income In The Past 12 Months Below Poverty Level,3636589,36473.785010,United States,01000US,united-states,0.064842
21,6,Other,2015,2015,0,Income In The Past 12 Months Below Poverty Level,3633067,35206.187130,United States,01000US,united-states,0.061936
22,6,Other,2017,2017,0,Income In The Past 12 Months Below Poverty Level,3297488,35802.858130,United States,01000US,united-states,0.061340
23,6,Other,2018,2018,0,Income In The Past 12 Months Below Poverty Level,3211683,36561.480810,United States,01000US,united-states,0.060738
24,4,Asian,2014,2014,0,Income In The Past 12 Months Below Poverty Level,2048589,24063.112990,United States,01000US,united-states,0.033426
25,4,Asian,2015,2015,0,Income In The Past 12 Months Below Poverty Level,2037183,23934.671320,United States,01000US,united-states,0.034729
26,4,Asian,2016,2016,0,Income In The Past 12 Months Below Poverty Level,2026897,24268.235970,United States,01000US,united-states,0.036141
27,4,Asian,2013,2013,0,Income In The Past 12 Months Below Poverty Level,2002107,24052.733980,United States,01000US,united-states,0.032344
28,4,Asian,2017,2017,0,Income In The Past 12 Months Below Poverty Level,1975913,25155.367800,United States,01000US,united-states,0.036756
29,4,Asian,2018,2018,0,Income In The Past 12 Months Below Poverty Level,1957779,25319.865070,United States,01000US,united-states,0.037025
30,7,Two Or More,2014,2014,0,Income In The Past 12 Months Below Poverty Level,1855585,23913.116460,United States,01000US,united-states,0.030276
31,7,Two Or More,2013,2013,0,Income In The Past 12 Months Below Poverty Level,1847715,24310.483970,United States,01000US,united-states,0.029850
32,7,Two Or More,2016,2016,0,Income In The Past 12 Months Below Poverty Level,1801745,24964.943820,United States,01000US,united-states,0.032126
33,7,Two Or More,2015,2015,0,Income In The Past 12 Months Below Poverty Level,1782109,23752.483300,United States,01000US,united-states,0.030381
34,7,Two Or More,2017,2017,0,Income In The Past 12 Months Below Poverty Level,1741395,24587.959110,United States,01000US,united-states,0.032394
35,7,Two Or More,2018,2018,0,Income In The Past 12 Months Below Poverty Level,1739271,25307.417410,United States,01000US,united-states,0.032892
36,3,Native American,2014,2014,0,Income In The Past 12 Months Below Poverty Level,710293,12070.178950,United States,01000US,united-states,0.011589
37,3,Native American,2013,2013,0,Income In The Past 12 Months Below Poverty Level,706256,11663.144340,United States,01000US,united-states,0.011410
38,3,Native American,2016,2016,0,Income In The Past 12 Months Below Poverty Level,679202,12328.646030,United States,01000US,united-states,0.012111
39,3,Native American,2017,2017,0,Income In The Past 12 Months Below Poverty Level,670571,12211.456380,United States,01000US,united-states,0.012474
40,3,Native American,2015,2015,0,Income In The Past 12 Months Below Poverty Level,665980,11763.899860,United States,01000US,united-states,0.011353
41,3,Native American,2018,2018,0,Income In The Past 12 Months Below Poverty Level,640066,12403.676190,United States,01000US,united-states,0.012105
42,5,Pacific Islander,2014,2014,0,Income In The Past 12 Months Below Poverty Level,112840,5756.902379,United States,01000US,united-states,0.001841
43,5,Pacific Islander,2017,2017,0,Income In The Past 12 Months Below Poverty Level,107762,6045.481619,United States,01000US,united-states,0.002005
44,5,Pacific Islander,2016,2016,0,Income In The Past 12 Months Below Poverty Level,104353,5774.867011,United States,01000US,united-states,0.001861
45,5,Pacific Islander,2013,2013,0,Income In The Past 12 Months Below Poverty Level,102153,5402.719593,United States,01000US,united-states,0.001650
46,5,Pacific Islander,2015,2015,0,Income In The Past 12 Months Below Poverty Level,101717,5681.786603,United States,01000US,united-states,0.001734
47,5,Pacific Islander,2018,2018,0,Income In The Past 12 Months Below Poverty Level,101584,6289.814703,United States,01000US,united-states,0.001921

In [74]:
#How many rows? 
len(povertyraw)

48

In [75]:
#Column Names?
povertyraw.columns

Index(['ID Race', 'Race', 'ID Year', 'Year', 'ID Poverty Status',
       'Poverty Status', 'Poverty Population',
       'Poverty Population Margin of Error(Moe)', 'Geography', 'ID Geography',
       'Slug Geography', 'share'],
      dtype='object')

In [76]:
#What are the Races?
povertyraw.Race.unique()

array(['White', 'Hispanic', 'Black', 'Other', 'Asian', 'Two Or More',
       'Native American', 'Pacific Islander'], dtype=object)

In [77]:
#Drop Unnecessary Columns
#Remove Other Race to match the single home chart 

RaceFilter = povertyraw.Race != 'Other'

poverty = povertyraw[RaceFilter].drop(['ID Race','ID Year','ID Poverty Status','Poverty Status','Poverty Population Margin of Error(Moe)', 'Geography', 'ID Geography', 'Slug Geography'], axis = 1)

In [78]:
#Columns of Data Frame poverty 
poverty.columns

Index(['Race', 'Year', 'Poverty Population', 'share'], dtype='object')

In [79]:
#Unique Races
poverty.Race.unique()

array(['White', 'Hispanic', 'Black', 'Asian', 'Two Or More',
       'Native American', 'Pacific Islander'], dtype=object)

In [80]:
#Rename the new data frame's columns
poverty.columns = ['Race', 'Year','PovertyPopulation', 'PercentofTotalPovertyPopulation']
poverty

                Race  Year  PovertyPopulation  PercentofTotalPovertyPopulation
0              White  2013           29701062                         0.479823
1              White  2014           29193983                         0.476341
2              White  2015           28027149                         0.477800
3              White  2016           26653418                         0.475246
4              White  2017           25668489                         0.477490
5              White  2018           25230693                         0.477151
6           Hispanic  2013           13089210                         0.211457
7           Hispanic  2014           13079584                         0.213412
8           Hispanic  2015           12505613                         0.213193
9           Hispanic  2016           11814468                         0.210659
10          Hispanic  2017           11173521                         0.207852
11          Hispanic  2018           11025445                         0.208508
12             Black  2013           10538290                         0.170247
13             Black  2014           10434389                         0.170252
14             Black  2015            9905872                         0.168873
15             Black  2016            9366792                         0.167015
16             Black  2017            9122033                         0.169690
17             Black  2018            8971239                         0.169660
24             Asian  2014            2048589                         0.033426
25             Asian  2015            2037183                         0.034729
26             Asian  2016            2026897                         0.036141
27             Asian  2013            2002107                         0.032344
28             Asian  2017            1975913                         0.036756
29             Asian  2018            1957779                         0.037025
30       Two Or More  2014            1855585                         0.030276
31       Two Or More  2013            1847715                         0.029850
32       Two Or More  2016            1801745                         0.032126
33       Two Or More  2015            1782109                         0.030381
34       Two Or More  2017            1741395                         0.032394
35       Two Or More  2018            1739271                         0.032892
36   Native American  2014             710293                         0.011589
37   Native American  2013             706256                         0.011410
38   Native American  2016             679202                         0.012111
39   Native American  2017             670571                         0.012474
40   Native American  2015             665980                         0.011353
41   Native American  2018             640066                         0.012105
42  Pacific Islander  2014             112840                         0.001841
43  Pacific Islander  2017             107762                         0.002005
44  Pacific Islander  2016             104353                         0.001861
45  Pacific Islander  2013             102153                         0.001650
46  Pacific Islander  2015             101717                         0.001734
47  Pacific Islander  2018             101584                         0.001921

In [81]:
#What are the data types of each column? 
poverty.info('columns')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 0 to 47
Data columns (total 4 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Race                             42 non-null     object
 1   Year                             42 non-null     int64
 2   PovertyPopulation                42 non-null     int64
 3   PercentofTotalPovertyPopulation  42 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.6+ KB

In [82]:
#Change Data Types. Make Race and Year categorical variables.  
poverty.Race = poverty.Race.astype('category')
poverty.Year = poverty.Year.astype('category')
poverty.info('columns')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 0 to 47
Data columns (total 4 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Race                             42 non-null     category
 1   Year                             42 non-null     category
 2   PovertyPopulation                42 non-null     int64
 3   PercentofTotalPovertyPopulation  42 non-null     float64
dtypes: category(2), float64(1), int64(1)
memory usage: 1.6 KB

In [83]:
#Multiply the values in the Percent Column by 100 to make them percentages
poverty.PercentofTotalPovertyPopulation = (poverty.PercentofTotalPovertyPopulation)*100
poverty

                Race  Year  PovertyPopulation  PercentofTotalPovertyPopulation
0              White  2013           29701062                        47.982269
1              White  2014           29193983                        47.634116
2              White  2015           28027149                        47.780046
3              White  2016           26653418                        47.524557
4              White  2017           25668489                        47.748957
5              White  2018           25230693                        47.715132
6           Hispanic  2013           13089210                        21.145708
7           Hispanic  2014           13079584                        21.341193
8           Hispanic  2015           12505613                        21.319284
9           Hispanic  2016           11814468                        21.065867
10          Hispanic  2017           11173521                        20.785173
11          Hispanic  2018           11025445                        20.850817
12             Black  2013           10538290                        17.024680
13             Black  2014           10434389                        17.025183
14             Black  2015            9905872                        16.887305
15             Black  2016            9366792                        16.701522
16             Black  2017            9122033                        16.968960
17             Black  2018            8971239                        16.965997
24             Asian  2014            2048589                         3.342563
25             Asian  2015            2037183                         3.472943
26             Asian  2016            2026897                         3.614072
27             Asian  2013            2002107                         3.234418
28             Asian  2017            1975913                         3.675627
29             Asian  2018            1957779                         3.702462
30       Two Or More  2014            1855585                         3.027650
31       Two Or More  2013            1847715                         2.984996
32       Two Or More  2016            1801745                         3.212614
33       Two Or More  2015            1782109                         3.038099
34       Two Or More  2017            1741395                         3.239372
35       Two Or More  2018            1739271                         3.289230
36   Native American  2014             710293                         1.158944
37   Native American  2013             706256                         1.140961
38   Native American  2016             679202                         1.211056
39   Native American  2017             670571                         1.247408
40   Native American  2015             665980                         1.135348
41   Native American  2018             640066                         1.210464
42  Pacific Islander  2014             112840                         0.184114
43  Pacific Islander  2017             107762                         0.200461
44  Pacific Islander  2016             104353                         0.186067
45  Pacific Islander  2013             102153                         0.165029
46  Pacific Islander  2015             101717                         0.173405
47  Pacific Islander  2018             101584                         0.192111

In [84]:
#Sum Asian and Pacific Islander Percentages 
yearlist = poverty.Year.unique().tolist()
AAPercent = []
PIPercent = []
for Y in yearlist:
    AAPercent.append(np.array(poverty[poverty.Year == Y][poverty.Race == 'Asian'].PercentofTotalPovertyPopulation))
    PIPercent.append(np.array(poverty[poverty.Year == Y][poverty.Race == 'Pacific Islander'].PercentofTotalPovertyPopulation))
    AAPIPercent = np.add(AAPercent,PIPercent)
AAPIPercent.tolist()

[[3.3994465000000003],
 [3.5266773],
 [3.6463480000000006],
 [3.8001397],
 [3.8760874999999992],
 [3.8945731]]

In [85]:
#Sum Asian and Pacific Islander Populations
AAPop = []
PIPop = []
for Y in yearlist:
    AAPop.append(np.array(poverty[poverty.Year == Y][poverty.Race == 'Asian'].PovertyPopulation))
    PIPop.append(np.array(poverty[poverty.Year == Y][poverty.Race == 'Pacific Islander'].PovertyPopulation))
    AAPIPop = np.add(AAPop,PIPop)
AAPIPop.tolist()

[[2104260], [2161429], [2138900], [2131250], [2083675], [2059363]]

In [86]:
#Insert New Rows for Asian and Pacific Islanders combined

In [87]:
#Create an AAPI list to place into dictionary  

a = '"Asian and Pacific Islander"'
def AAPIfunc():
    counter = 0
    while counter < 6:
            print(counter,':', a , ',', end = ' ')
            counter = counter + 1 
AAPIfunc()

0 : "Asian and Pacific Islander" , 1 : "Asian and Pacific Islander" , 2 : "Asian and Pacific Islander" , 3 : "Asian and Pacific Islander" , 4 : "Asian and Pacific Islander" , 5 : "Asian and Pacific Islander" ,

In [88]:
#Create a Population list to enter into a dictionary
poplist = [2104260, 2161429, 2138900, 2131250, 2083675, 2059363]
def popfunc():
    counter = 0
    while counter < 6: 
            for p in poplist:
                    print(counter, ':', p,',', end = ' ')
                    counter = counter +1 
popfunc()

0 : 2104260 , 1 : 2161429 , 2 : 2138900 , 3 : 2131250 , 4 : 2083675 , 5 : 2059363 ,

In [89]:
#Create a dictionary for list AAPI 
AAPIdict = {0 : "Asian and Pacific Islander" , 1 : "Asian and Pacific Islander" , 2 : "Asian and Pacific Islander" ,
            3 : "Asian and Pacific Islander" , 4 : "Asian and Pacific Islander" , 5 : "Asian and Pacific Islander"}

#test the dictionary
AAPIdict[2]

'Asian and Pacific Islander'

In [90]:
#Create a Year list to put into a dictionary

years = poverty.Year.unique().tolist()
def yearfunc():
    counter = 0
    while counter < 6: 
            for y in years:
                    print(counter, ':', y,',', end = ' ')
                    counter = counter +1 
yearfunc()

0 : 2013 , 1 : 2014 , 2 : 2015 , 3 : 2016 , 4 : 2017 , 5 : 2018 ,

In [91]:
#Create a Dictionary for Years
Yeardict = {0 : 2013 , 1 : 2014 , 2 : 2015 , 3 : 2016 , 4 : 2017 , 5 : 2018}
#Test Dictionary 
Yeardict[4]

2017

In [92]:
#Create a Dictionary for Percentages
percentages = AAPIPercent.tolist()
def percentfunc():
    counter = 0
    while counter < 6:
        for p in percentages:
            print(counter, ':', p,',', end = ' ')
            counter = counter + 1
percentfunc()

0 : [3.3994465000000003] , 1 : [3.5266773] , 2 : [3.6463480000000006] , 3 : [3.8001397] , 4 : [3.8760874999999992] , 5 : [3.8945731] ,

In [93]:
Percentdict = {0 : [3.3994465000000003] , 1 : [3.5266773] , 2 : [3.6463480000000006] , 
               3 : [3.8001397] , 4 : [3.8760874999999992] , 5 : [3.8945731]}
Percentdict[0]

[3.3994465000000003]

In [94]:
#Define function to insert new rows into data frame
numberlist = [0,1,2,3,4,5]
AAPIdict = {0 : "Asian and Pacific Islander" , 1 : "Asian and Pacific Islander" , 2 : "Asian and Pacific Islander" ,
            3 : "Asian and Pacific Islander" , 4 : "Asian and Pacific Islander" , 5 : "Asian and Pacific Islander"}
Yeardict = {0 : 2013 , 1 : 2014 , 2 : 2015 , 3 : 2016 , 4 : 2017 , 5 : 2018}
Populationdict = {0 : 2104260 , 1 : 2161429 , 2 : 2138900 , 3 : 2131250 , 4 : 2083675 , 5 : 2059363 }
Percentdict = {0 : 3.3994465000000003 , 1 : 3.5266773 , 2 : 3.6463480000000006 , 
               3 : 3.8001397 , 4 : 3.8760874999999992 , 5 : 3.8945731}

for n in numberlist:
    new_row = {'Race':AAPIdict[n], 'Year':Yeardict[n], 'PovertyPopulation':Populationdict[n],'PercentofTotalPovertyPopulation':Percentdict[n]}
    poverty = poverty.append(new_row, ignore_index=True)

In [95]:
#Drop original Asian rows`

index_Asian = poverty[poverty.Race == 'Asian'].index
poverty.drop(index_Asian, inplace = True)
poverty.Race.unique()

array(['White', 'Hispanic', 'Black', 'Two Or More', 'Native American',
       'Pacific Islander', 'Asian and Pacific Islander'], dtype=object)

In [96]:
#Drop original Pacific Islander Rows
index_Pacific = poverty[poverty.Race == 'Pacific Islander'].index
poverty.drop(index_Pacific, inplace = True)
poverty.Race.unique()

array(['White', 'Hispanic', 'Black', 'Two Or More', 'Native American',
       'Asian and Pacific Islander'], dtype=object)

In [97]:
#Round Percent Decimal Points
poverty.PercentofTotalPovertyPopulation = np.round(poverty.PercentofTotalPovertyPopulation,2)

In [98]:
#What are the unique races? 
poverty.Race.unique()

array(['White', 'Hispanic', 'Black', 'Two Or More', 'Native American',
       'Asian and Pacific Islander'], dtype=object)

In [99]:
#Replace Two or More with Multiracial
poverty.Race = poverty.Race.replace('Two Or More','Multiracial')

In [100]:
poverty.columns

Index(['Race', 'Year', 'PovertyPopulation', 'PercentofTotalPovertyPopulation'], dtype='object')

In [101]:
#Change Column Names Again For Export to be joined with other dataframes in SQL
poverty.columns = ['Race', 'Year','Poverty Population', 'Percent of Total Poverty Population']

In [102]:
#Drop the year 2018
index_years = poverty[poverty.Year == 2018].index
poverty.drop(index_years, inplace = True)
poverty.Year.unique().tolist()

[2013, 2014, 2015, 2016, 2017]

---

---

In [103]:
#Final Data Frames vs Original Raw Data Frames

In [104]:
#Raw education data
educationraw

,ID IPEDS Race,IPEDS Race,ID Year,Year,Completions,Geography,ID Geography,Slug Geography,share
0,asian,Asian,2017,2017,298112,United States,01000US,united-states,0.061655
1,black,Black or African American,2017,2017,576612,United States,01000US,united-states,0.119254
2,hawaiian,Native Hawaiian or Other Pacific Islanders,2017,2017,14034,United States,01000US,united-states,0.002902
3,hispanic,Hispanic or Latino,2017,2017,786273,United States,01000US,united-states,0.162616
4,multiracial,Two or More Races,2017,2017,141479,United States,01000US,united-states,0.029260
5,native,American Indian or Alaska Native,2017,2017,33272,United States,01000US,united-states,0.006881
6,unknown,Unknown,2017,2017,220035,United States,01000US,united-states,0.045507
7,white,White,2017,2017,2765344,United States,01000US,united-states,0.571924
8,asian,Asian,2016,2016,284589,United States,01000US,united-states,0.059460
9,black,Black or African American,2016,2016,576255,United States,01000US,united-states,0.120399
10,hawaiian,Native Hawaiian or Other Pacific Islanders,2016,2016,13976,United States,01000US,united-states,0.002920
11,hispanic,Hispanic or Latino,2016,2016,740025,United States,01000US,united-states,0.154616
12,multiracial,Two or More Races,2016,2016,132024,United States,01000US,united-states,0.027584
13,native,American Indian or Alaska Native,2016,2016,33193,United States,01000US,united-states,0.006935
14,unknown,Unknown,2016,2016,238703,United States,01000US,united-states,0.049873
15,white,White,2016,2016,2767440,United States,01000US,united-states,0.578212
16,asian,Asian,2015,2015,273957,United States,01000US,united-states,0.057770
17,black,Black or African American,2015,2015,573638,United States,01000US,united-states,0.120964
18,hawaiian,Native Hawaiian or Other Pacific Islanders,2015,2015,14420,United States,01000US,united-states,0.003041
19,hispanic,Hispanic or Latino,2015,2015,687513,United States,01000US,united-states,0.144977
20,multiracial,Two or More Races,2015,2015,116276,United States,01000US,united-states,0.024519
21,native,American Indian or Alaska Native,2015,2015,33936,United States,01000US,united-states,0.007156
22,unknown,Unknown,2015,2015,252299,United States,01000US,united-states,0.053203
23,white,White,2015,2015,2790167,United States,01000US,united-states,0.588369
24,asian,Asian,2014,2014,264271,United States,01000US,united-states,0.056585
25,black,Black or African American,2014,2014,556705,United States,01000US,united-states,0.119201
26,hawaiian,Native Hawaiian or Other Pacific Islanders,2014,2014,14788,United States,01000US,united-states,0.003166
27,hispanic,Hispanic or Latino,2014,2014,638188,United States,01000US,united-states,0.136648
28,multiracial,Two or More Races,2014,2014,99685,United States,01000US,united-states,0.021344
29,native,American Indian or Alaska Native,2014,2014,34050,United States,01000US,united-states,0.007291
30,unknown,Unknown,2014,2014,270672,United States,01000US,united-states,0.057956
31,white,White,2014,2014,2791956,United States,01000US,united-states,0.597809
32,asian,Asian,2013,2013,257662,United States,01000US,united-states,0.056985
33,black,Black or African American,2013,2013,529285,United States,01000US,united-states,0.117059
34,hawaiian,Native Hawaiian or Other Pacific Islanders,2013,2013,14418,United States,01000US,united-states,0.003189
35,hispanic,Hispanic or Latino,2013,2013,589993,United States,01000US,united-states,0.130485
36,multiracial,Two or More Races,2013,2013,78724,United States,01000US,united-states,0.017411
37,native,American Indian or Alaska Native,2013,2013,34147,United States,01000US,united-states,0.007552
38,unknown,Unknown,2013,2013,263664,United States,01000US,united-states,0.058313
39,white,White,2013,2013,2753647,United States,01000US,united-states,0.609006
40,asian,Asian,2012,2012,248208,United States,01000US,united-states,0.055863
41,black,Black or African American,2012,2012,516275,United States,01000US,united-states,0.116195
42,hawaiian,Native Hawaiian or Other Pacific Islanders,2012,2012,13635,United States,01000US,united-states,0.003069
43,hispanic,Hispanic or Latino,2012,2012,550949,United States,01000US,united-states,0.123999
44,multiracial,Two or More Races,2012,2012,61313,United States,01000US,united-states,0.013799
45,native,American Indian or Alaska Native,2012,2012,33366,United States,01000US,united-states,0.007510
46,unknown,Unknown,2012,2012,291882,United States,01000US,united-states,0.065692
47,white,White,2012,2012,2727541,United States,01000US,united-states,0.613873

In [105]:
#Final Cleaned and Mined education data 
education

                          Race  Year  DegreesCompleted  PercentofTotalDegrees
1                        Black  2017            576612                  11.93
3                     Hispanic  2017            786273                  16.26
4                  Multiracial  2017            141479                   2.93
5              Native American  2017             33272                   0.69
6                        White  2017           2765344                  57.19
8                        Black  2016            576255                  12.04
10                    Hispanic  2016            740025                  15.46
11                 Multiracial  2016            132024                   2.76
12             Native American  2016             33193                   0.69
13                       White  2016           2767440                  57.82
15                       Black  2015            573638                  12.10
17                    Hispanic  2015            687513                  14.50
18                 Multiracial  2015            116276                   2.45
19             Native American  2015             33936                   0.72
20                       White  2015           2790167                  58.84
22                       Black  2014            556705                  11.92
24                    Hispanic  2014            638188                  13.66
25                 Multiracial  2014             99685                   2.13
26             Native American  2014             34050                   0.73
27                       White  2014           2791956                  59.78
29                       Black  2013            529285                  11.71
31                    Hispanic  2013            589993                  13.05
32                 Multiracial  2013             78724                   1.74
33             Native American  2013             34147                   0.76
34                       White  2013           2753647                  60.90
36                       Black  2012            516275                  11.62
38                    Hispanic  2012            550949                  12.40
39                 Multiracial  2012             61313                   1.38
40             Native American  2012             33366                   0.75
41                       White  2012           2727541                  61.39
42  Asian and Pacific Islander  2017            312146                   6.46
43  Asian and Pacific Islander  2016            298565                   6.24
44  Asian and Pacific Islander  2015            288377                   6.08
45  Asian and Pacific Islander  2014            279059                   5.98
46  Asian and Pacific Islander  2013            272080                   6.02
47  Asian and Pacific Islander  2012            261843                   5.89

---

In [106]:
#Raw Children in Single Parent Homes Data
singleparentkidsraw

,LocationType,Location,Race,Year,DataFormat,TotalChildren
0,Nation,United States,American Indian,2005,Percent,0.49
1,Nation,United States,Asian and Pacific Islander,2005,Percent,0.17
2,Nation,United States,Black or African American,2005,Percent,0.65
3,Nation,United States,Hispanic or Latino,2005,Percent,0.36
4,Nation,United States,Non-Hispanic White,2005,Percent,0.23
...,...,...,...,...,...,...
11077,Territory,Puerto Rico,Non-Hispanic White,2019,Number,S
11078,Territory,Puerto Rico,Hispanic or Latino,2019,Number,341000
11079,Territory,Puerto Rico,Black or African American,2019,Number,44000
11080,Territory,Puerto Rico,Asian and Pacific Islander,2019,Number,S
11081,Territory,Puerto Rico,American Indian,2019,Number,S

In [107]:
#Final Cleaned and Mined Children in Single Parent Homes Data Frame 
singleparentkids

,Race,Year,Number of Children(Single Parent Homes),Percent of Total Children(Single Parent Homes)
63,Native American,2013,329000,1.30
64,Asian and Pacific Islander,2013,557000,2.19
65,Black,2013,6427000,25.30
66,Hispanic,2013,7044000,27.73
67,White,2013,9289000,36.57
68,Multiracial,2013,1758000,6.92
127,Multiracial,2015,1804000,7.15
128,White,2015,8998000,35.68
129,Hispanic,2015,7180000,28.47
130,Black,2015,6333000,25.12
131,Asian and Pacific Islander,2015,568000,2.25
132,Native American,2015,333000,1.32
154,Native American,2014,341000,1.34
155,Asian and Pacific Islander,2014,578000,2.27
156,Black,2014,6382000,25.06
157,Hispanic,2014,7190000,28.23
158,White,2014,9181000,36.05
159,Multiracial,2014,1797000,7.06
176,Multiracial,2016,1900000,7.57
177,White,2016,8766000,34.94
178,Hispanic,2016,7230000,28.82
179,Black,2016,6281000,25.04
180,Asian and Pacific Islander,2016,572000,2.28
181,Native American,2016,339000,1.35
183,Multiracial,2017,1887000,7.60
184,White,2017,8623000,34.74
185,Hispanic,2017,7283000,29.34
186,Black,2017,6123000,24.67
187,Asian and Pacific Islander,2017,556000,2.24
188,Native American,2017,351000,1.41

---

In [108]:
#Raw Poverty Population by Race Data
povertyraw

,ID Race,Race,ID Year,Year,ID Poverty Status,Poverty Status,Poverty Population,Poverty Population Margin of Error(Moe),Geography,ID Geography,Slug Geography,share
0,1,White,2013,2013,0,Income In The Past 12 Months Below Poverty Level,29701062,97115.895530,United States,01000US,united-states,0.479823
1,1,White,2014,2014,0,Income In The Past 12 Months Below Poverty Level,29193983,92676.176460,United States,01000US,united-states,0.476341
2,1,White,2015,2015,0,Income In The Past 12 Months Below Poverty Level,28027149,95135.243000,United States,01000US,united-states,0.477800
3,1,White,2016,2016,0,Income In The Past 12 Months Below Poverty Level,26653418,92998.998830,United States,01000US,united-states,0.475246
4,1,White,2017,2017,0,Income In The Past 12 Months Below Poverty Level,25668489,89754.419970,United States,01000US,united-states,0.477490
5,1,White,2018,2018,0,Income In The Past 12 Months Below Poverty Level,25230693,90255.224380,United States,01000US,united-states,0.477151
6,9,Hispanic,2013,2013,0,Income In The Past 12 Months Below Poverty Level,13089210,60768.446300,United States,01000US,united-states,0.211457
7,9,Hispanic,2014,2014,0,Income In The Past 12 Months Below Poverty Level,13079584,60525.658200,United States,01000US,united-states,0.213412
8,9,Hispanic,2015,2015,0,Income In The Past 12 Months Below Poverty Level,12505613,63334.284890,United States,01000US,united-states,0.213193
9,9,Hispanic,2016,2016,0,Income In The Past 12 Months Below Poverty Level,11814468,61008.833560,United States,01000US,united-states,0.210659
10,9,Hispanic,2017,2017,0,Income In The Past 12 Months Below Poverty Level,11173521,60557.196800,United States,01000US,united-states,0.207852
11,9,Hispanic,2018,2018,0,Income In The Past 12 Months Below Poverty Level,11025445,64930.124110,United States,01000US,united-states,0.208508
12,2,Black,2013,2013,0,Income In The Past 12 Months Below Poverty Level,10538290,54162.147670,United States,01000US,united-states,0.170247
13,2,Black,2014,2014,0,Income In The Past 12 Months Below Poverty Level,10434389,55886.169110,United States,01000US,united-states,0.170252
14,2,Black,2015,2015,0,Income In The Past 12 Months Below Poverty Level,9905872,55994.616540,United States,01000US,united-states,0.168873
15,2,Black,2016,2016,0,Income In The Past 12 Months Below Poverty Level,9366792,55843.164860,United States,01000US,united-states,0.167015
16,2,Black,2017,2017,0,Income In The Past 12 Months Below Poverty Level,9122033,58930.514780,United States,01000US,united-states,0.169690
17,2,Black,2018,2018,0,Income In The Past 12 Months Below Poverty Level,8971239,58040.756140,United States,01000US,united-states,0.169660
18,6,Other,2013,2013,0,Income In The Past 12 Months Below Poverty Level,3913285,37953.370760,United States,01000US,united-states,0.063219
19,6,Other,2014,2014,0,Income In The Past 12 Months Below Poverty Level,3852708,34912.027150,United States,01000US,united-states,0.062862
20,6,Other,2016,2016,0,Income In The Past 12 Months Below Poverty Level,3636589,36473.785010,United States,01000US,united-states,0.064842
21,6,Other,2015,2015,0,Income In The Past 12 Months Below Poverty Level,3633067,35206.187130,United States,01000US,united-states,0.061936
22,6,Other,2017,2017,0,Income In The Past 12 Months Below Poverty Level,3297488,35802.858130,United States,01000US,united-states,0.061340
23,6,Other,2018,2018,0,Income In The Past 12 Months Below Poverty Level,3211683,36561.480810,United States,01000US,united-states,0.060738
24,4,Asian,2014,2014,0,Income In The Past 12 Months Below Poverty Level,2048589,24063.112990,United States,01000US,united-states,0.033426
25,4,Asian,2015,2015,0,Income In The Past 12 Months Below Poverty Level,2037183,23934.671320,United States,01000US,united-states,0.034729
26,4,Asian,2016,2016,0,Income In The Past 12 Months Below Poverty Level,2026897,24268.235970,United States,01000US,united-states,0.036141
27,4,Asian,2013,2013,0,Income In The Past 12 Months Below Poverty Level,2002107,24052.733980,United States,01000US,united-states,0.032344
28,4,Asian,2017,2017,0,Income In The Past 12 Months Below Poverty Level,1975913,25155.367800,United States,01000US,united-states,0.036756
29,4,Asian,2018,2018,0,Income In The Past 12 Months Below Poverty Level,1957779,25319.865070,United States,01000US,united-states,0.037025
30,7,Two Or More,2014,2014,0,Income In The Past 12 Months Below Poverty Level,1855585,23913.116460,United States,01000US,united-states,0.030276
31,7,Two Or More,2013,2013,0,Income In The Past 12 Months Below Poverty Level,1847715,24310.483970,United States,01000US,united-states,0.029850
32,7,Two Or More,2016,2016,0,Income In The Past 12 Months Below Poverty Level,1801745,24964.943820,United States,01000US,united-states,0.032126
33,7,Two Or More,2015,2015,0,Income In The Past 12 Months Below Poverty Level,1782109,23752.483300,United States,01000US,united-states,0.030381
34,7,Two Or More,2017,2017,0,Income In The Past 12 Months Below Poverty Level,1741395,24587.959110,United States,01000US,united-states,0.032394
35,7,Two Or More,2018,2018,0,Income In The Past 12 Months Below Poverty Level,1739271,25307.417410,United States,01000US,united-states,0.032892
36,3,Native American,2014,2014,0,Income In The Past 12 Months Below Poverty Level,710293,12070.178950,United States,01000US,united-states,0.011589
37,3,Native American,2013,2013,0,Income In The Past 12 Months Below Poverty Level,706256,11663.144340,United States,01000US,united-states,0.011410
38,3,Native American,2016,2016,0,Income In The Past 12 Months Below Poverty Level,679202,12328.646030,United States,01000US,united-states,0.012111
39,3,Native American,2017,2017,0,Income In The Past 12 Months Below Poverty Level,670571,12211.456380,United States,01000US,united-states,0.012474
40,3,Native American,2015,2015,0,Income In The Past 12 Months Below Poverty Level,665980,11763.899860,United States,01000US,united-states,0.011353
41,3,Native American,2018,2018,0,Income In The Past 12 Months Below Poverty Level,640066,12403.676190,United States,01000US,united-states,0.012105
42,5,Pacific Islander,2014,2014,0,Income In The Past 12 Months Below Poverty Level,112840,5756.902379,United States,01000US,united-states,0.001841
43,5,Pacific Islander,2017,2017,0,Income In The Past 12 Months Below Poverty Level,107762,6045.481619,United States,01000US,united-states,0.002005
44,5,Pacific Islander,2016,2016,0,Income In The Past 12 Months Below Poverty Level,104353,5774.867011,United States,01000US,united-states,0.001861
45,5,Pacific Islander,2013,2013,0,Income In The Past 12 Months Below Poverty Level,102153,5402.719593,United States,01000US,united-states,0.001650
46,5,Pacific Islander,2015,2015,0,Income In The Past 12 Months Below Poverty Level,101717,5681.786603,United States,01000US,united-states,0.001734
47,5,Pacific Islander,2018,2018,0,Income In The Past 12 Months Below Poverty Level,101584,6289.814703,United States,01000US,united-states,0.001921

In [109]:
#Final Cleaned and Mined Poverty Population by Race Data Frame 
poverty

,Race,Year,Poverty Population,Percent of Total Poverty Population
0,White,2013,29701062,47.98
1,White,2014,29193983,47.63
2,White,2015,28027149,47.78
3,White,2016,26653418,47.52
4,White,2017,25668489,47.75
6,Hispanic,2013,13089210,21.15
7,Hispanic,2014,13079584,21.34
8,Hispanic,2015,12505613,21.32
9,Hispanic,2016,11814468,21.07
10,Hispanic,2017,11173521,20.79
12,Black,2013,10538290,17.02
13,Black,2014,10434389,17.03
14,Black,2015,9905872,16.89
15,Black,2016,9366792,16.70
16,Black,2017,9122033,16.97
24,Multiracial,2014,1855585,3.03
25,Multiracial,2013,1847715,2.98
26,Multiracial,2016,1801745,3.21
27,Multiracial,2015,1782109,3.04
28,Multiracial,2017,1741395,3.24
30,Native American,2014,710293,1.16
31,Native American,2013,706256,1.14
32,Native American,2016,679202,1.21
33,Native American,2017,670571,1.25
34,Native American,2015,665980,1.14
42,Asian and Pacific Islander,2013,2104260,3.40
43,Asian and Pacific Islander,2014,2161429,3.53
44,Asian and Pacific Islander,2015,2138900,3.65
45,Asian and Pacific Islander,2016,2131250,3.80
46,Asian and Pacific Islander,2017,2083675,3.88

---

---

In [110]:
#Export Data Frames as CSVs

In [111]:
#Export education Data Frame as a CSV
#education.to_csv('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Created CSV Files/2012-2017_Degrees_Completed_By_Race.csv')

In [112]:
#Export Single Parent Kids Data Frame as a CSV
#singleparentkids.to_csv('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Created CSV Files/2010-2019_Single_Parent_Children_By_Race.csv')

In [113]:
#Export New Data Frame as CSV 
#poverty.to_csv('C:\\Users\zara\Documents/Data Science Portfolio_Zara Clacken/Created CSV Files/2013-2018_Poverty_By_Race.csv')