In [702]:
#Import Libraries
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn
seaborn.set()

In [669]:
#Check Directory
os.getcwd()

'C:\\Users\\zara\\Documents\\Data Science Portfolio_Zara Clacken\\MBA 701 Econ Assignments Redone in R & Python'

In [670]:
#Import Data Frame 
crimestats = pd.read_excel("State Crime.xlsx")

# Data Mining and Cleaning

In [671]:
#Check the head of the data frame 
crimestats.head()

,"Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,Violent crime,Aggravated assault,Murder and nonnegligent manslaughter,Robbery,Property crime,Burglary,Larceny-theft,Motor vehicle theft,NaN,...,"average annual temperature, degrees F",# of sunny days per year,"average annual rainfall, inches",% living in same house one year ago,Median age,"Median age, Male","Median age, Female","% 18-24/18-64, % of the 18-to-64 year old popu...","% male 18-24/18-64, % of the 18-to-64 year old...","% female 18-24/18-64, % of the 18-to-64 year o..."
1,https://ucr.fbi.gov/crime-in-the-u.s/2019/crim...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,NaN,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
3,ALABAMA,510.8,381,7.3,80.4,2674.4,531.9,1886.1,256.5,NaN,...,62.8,99,58.3,86.2748,39,36.9,39.8,0.162112,0.166881,0.157552
4,ARIZONA,455.3,311.9,5,88.1,2440.5,394.3,1796.9,249.4,NaN,...,60.3,193,13.6,82.5992,37.7,35.5,38.1,0.167072,0.172756,0.16136

In [672]:
#Count number of Rows 
len(crimestats)

51

In [673]:
#Drop Row 0 and 1 since they are not important
crimestats = crimestats[2:51] #note, this calls rows by index number

In [674]:
#Check the head once again 
crimestats.head()

,"Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
2,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,NaN,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
3,ALABAMA,510.8,381,7.3,80.4,2674.4,531.9,1886.1,256.5,NaN,...,62.8,99,58.3,86.2748,39,36.9,39.8,0.162112,0.166881,0.157552
4,ARIZONA,455.3,311.9,5,88.1,2440.5,394.3,1796.9,249.4,NaN,...,60.3,193,13.6,82.5992,37.7,35.5,38.1,0.167072,0.172756,0.16136
5,ARKANSAS,584.6,447.8,8,51.6,2858,599.6,2012.6,245.9,NaN,...,60.4,123,50.6,84.5835,38.1,36.3,39,0.161854,0.166034,0.157748
6,CALIFORNIA,441.2,267.1,4.3,132.4,2331.2,386.1,1586.3,358.8,NaN,...,59.4,146,22.2,87.1416,36.5,34.6,37,0.164324,0.168907,0.1597

In [675]:
#Check the tail as well 
crimestats.tail()

,"Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
46,VIRGINIA,208,128.7,5,41.3,1642.7,162.8,1359.5,120.3,NaN,...,55.1,100,44.3,84.7435,38.2,36.4,39,0.155201,0.160974,0.149525
47,WASHINGTON,293.9,179.9,2.6,67.6,2681.9,453.6,1907.9,320.5,NaN,...,48.3,58,38.4,82.2926,37.7,36.5,38.6,0.150181,0.154585,0.145705
48,WEST VIRGINIA,316.6,249.1,4.4,21.1,1583.4,328.7,1119.7,135,NaN,...,51.8,60,45.2,88.3447,42.5,40.5,43,0.149907,0.153518,0.146275
49,WISCONSIN,293.2,200,3,51.4,1471.4,217.6,1127,126.8,NaN,...,43.1,89,32.6,86.0183,39.5,37.8,40.1,0.157127,0.159034,0.155191
50,WYOMING,217.4,147.6,2.2,11.6,1571.1,241.2,1206.7,123.2,NaN,...,42,114,12.9,83.1709,37.7,36.1,37.6,0.160349,0.163652,0.156804

In [676]:
#Count rows after subsetting
len(crimestats)

49

In [677]:
#Call Row 2 and name it as object row 2 
row2 = crimestats.loc[[2]] #call row by the label number

In [678]:
#Turn Row 2 into an Array and make it an object
newcolumnnames = np.array(row2)

In [679]:
#check array
print(newcolumnnames)

[['State' 'Violent' 'Assault' 'Murder' 'Robbery' 'PropCrime' 'Burglary'
  'Larceny' 'CarTheft' nan 'Population' 'PerCapIncome' '%Metro'
  '%Bachelors+' '%Unemploy' '%Poverty' 'Temp' 'Sun' 'Rain' '%SameHouse'
  'MedianAge' 'MedAgeMale' 'MedAgeFemale' '%young' '%youngmale'
  '%youngfemale']]

In [680]:
print(newcolumnnames.tolist())

[['State', 'Violent', 'Assault', 'Murder', 'Robbery', 'PropCrime', 'Burglary', 'Larceny', 'CarTheft', nan, 'Population', 'PerCapIncome', '%Metro', '%Bachelors+', '%Unemploy', '%Poverty', 'Temp', 'Sun', 'Rain', '%SameHouse', 'MedianAge', 'MedAgeMale', 'MedAgeFemale', '%young', '%youngmale', '%youngfemale']]

In [681]:
#Convert Original Columns Names into an Array 
np.array(crimestats.columns)

array(['Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9',
       'Non-crime variables; units are as specified in row 2 descriptors',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25'], dtype=object)

---

In [682]:
#Check indexing
crimestats.iloc[0,0]

'State'

In [683]:
#Check Indexing 
crimestats.columns[0]

'Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants'

In [684]:
#Create a function for a dictionary to input into column rename function 
def namefunc():
    n = range(26)
    for i in n:
        newname = np.array(crimestats.iloc[0,i]).tolist()
        oldname = np.array(crimestats.columns[i]).tolist()
        columndict = {print("\"%s\""%oldname,":","\"%s\""%newname,",",end = " ")}  
namefunc()

"Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants" : "State" , "Unnamed: 1" : "Violent" , "Unnamed: 2" : "Assault" , "Unnamed: 3" : "Murder" , "Unnamed: 4" : "Robbery" , "Unnamed: 5" : "PropCrime" , "Unnamed: 6" : "Burglary" , "Unnamed: 7" : "Larceny" , "Unnamed: 8" : "CarTheft" , "Unnamed: 9" : "nan" , "Non-crime variables; units are as specified in row 2 descriptors" : "Population" , "Unnamed: 11" : "PerCapIncome" , "Unnamed: 12" : "%Metro" , "Unnamed: 13" : "%Bachelors+" , "Unnamed: 14" : "%Unemploy" , "Unnamed: 15" : "%Poverty" , "Unnamed: 16" : "Temp" , "Unnamed: 17" : "Sun" , "Unnamed: 18" : "Rain" , "Unnamed: 19" : "%SameHouse" , "Unnamed: 20" : "MedianAge" , "Unnamed: 21" : "MedAgeMale" , "Unnamed: 22" : "MedAgeFemale" , "Unnamed: 23" : "%young" , "Unnamed: 24" : "%youngmale" , "Unnamed: 25" : "%youngfemale" ,

In [685]:
columndict

{'Table 5, Crime in the United States by State, 2019, Rate per 100,000 inhabitants': 'State',
 'Unnamed: 1': 'Violent',
 'Unnamed: 2': 'Assault',
 'Unnamed: 3': 'Murder',
 'Unnamed: 4': 'Robbery',
 'Unnamed: 5': 'PropCrime',
 'Unnamed: 6': 'Burglary',
 'Unnamed: 7': 'Larceny',
 'Unnamed: 8': 'CarTheft',
 'Unnamed: 9': 'nan',
 'Non-crime variables; units are as specified in row 2 descriptors': 'Population',
 'Unnamed: 11': 'PerCapIncome',
 'Unnamed: 12': '%Metro',
 'Unnamed: 13': '%Bachelors+',
 'Unnamed: 14': '%Unemploy',
 'Unnamed: 15': '%Poverty',
 'Unnamed: 16': 'Temp',
 'Unnamed: 17': 'Sun',
 'Unnamed: 18': 'Rain',
 'Unnamed: 19': '%SameHouse',
 'Unnamed: 20': 'MedianAge',
 'Unnamed: 21': 'MedAgeMale',
 'Unnamed: 22': 'MedAgeFemale',
 'Unnamed: 23': '%young',
 'Unnamed: 24': '%youngmale',
 'Unnamed: 25': '%youngfemale'}

In [686]:
#rename data frame's columns using dictionary 
crimestats = crimestats.rename(columns=columndict)

In [687]:
#Check if data frames column names have changed
crimestats.head()

,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,nan,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
2,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,NaN,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
3,ALABAMA,510.8,381,7.3,80.4,2674.4,531.9,1886.1,256.5,NaN,...,62.8,99,58.3,86.2748,39,36.9,39.8,0.162112,0.166881,0.157552
4,ARIZONA,455.3,311.9,5,88.1,2440.5,394.3,1796.9,249.4,NaN,...,60.3,193,13.6,82.5992,37.7,35.5,38.1,0.167072,0.172756,0.16136
5,ARKANSAS,584.6,447.8,8,51.6,2858,599.6,2012.6,245.9,NaN,...,60.4,123,50.6,84.5835,38.1,36.3,39,0.161854,0.166034,0.157748
6,CALIFORNIA,441.2,267.1,4.3,132.4,2331.2,386.1,1586.3,358.8,NaN,...,59.4,146,22.2,87.1416,36.5,34.6,37,0.164324,0.168907,0.1597

In [688]:
#Drop Row Label 2 
crimestats = crimestats.drop(2, 0) #2 is the label and 0 indicates a row is being dropped

In [689]:
#Check head again
crimestats.head()

,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,nan,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
3,ALABAMA,510.8,381,7.3,80.4,2674.4,531.9,1886.1,256.5,NaN,...,62.8,99,58.3,86.2748,39,36.9,39.8,0.162112,0.166881,0.157552
4,ARIZONA,455.3,311.9,5,88.1,2440.5,394.3,1796.9,249.4,NaN,...,60.3,193,13.6,82.5992,37.7,35.5,38.1,0.167072,0.172756,0.16136
5,ARKANSAS,584.6,447.8,8,51.6,2858,599.6,2012.6,245.9,NaN,...,60.4,123,50.6,84.5835,38.1,36.3,39,0.161854,0.166034,0.157748
6,CALIFORNIA,441.2,267.1,4.3,132.4,2331.2,386.1,1586.3,358.8,NaN,...,59.4,146,22.2,87.1416,36.5,34.6,37,0.164324,0.168907,0.1597
7,COLORADO,381,246.3,3.8,63.6,2590.7,348.4,1858.3,384,NaN,...,45.1,136,15.9,82.0307,36.7,35.5,37.5,0.15041,0.154748,0.145948

In [690]:
#Check Tail Again 
crimestats.tail()

,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,nan,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
46,VIRGINIA,208,128.7,5,41.3,1642.7,162.8,1359.5,120.3,NaN,...,55.1,100,44.3,84.7435,38.2,36.4,39,0.155201,0.160974,0.149525
47,WASHINGTON,293.9,179.9,2.6,67.6,2681.9,453.6,1907.9,320.5,NaN,...,48.3,58,38.4,82.2926,37.7,36.5,38.6,0.150181,0.154585,0.145705
48,WEST VIRGINIA,316.6,249.1,4.4,21.1,1583.4,328.7,1119.7,135,NaN,...,51.8,60,45.2,88.3447,42.5,40.5,43,0.149907,0.153518,0.146275
49,WISCONSIN,293.2,200,3,51.4,1471.4,217.6,1127,126.8,NaN,...,43.1,89,32.6,86.0183,39.5,37.8,40.1,0.157127,0.159034,0.155191
50,WYOMING,217.4,147.6,2.2,11.6,1571.1,241.2,1206.7,123.2,NaN,...,42,114,12.9,83.1709,37.7,36.1,37.6,0.160349,0.163652,0.156804

In [691]:
#Drop the column with NaN values which is column index number 9 
crimestats = crimestats.drop("nan", 1)

In [692]:
crimestats.head()

,State,Violent,Assault,Murder,Robbery,PropCrime,Burglary,Larceny,CarTheft,Population,...,Temp,Sun,Rain,%SameHouse,MedianAge,MedAgeMale,MedAgeFemale,%young,%youngmale,%youngfemale
3,ALABAMA,510.8,381,7.3,80.4,2674.4,531.9,1886.1,256.5,4903185,...,62.8,99,58.3,86.2748,39,36.9,39.8,0.162112,0.166881,0.157552
4,ARIZONA,455.3,311.9,5,88.1,2440.5,394.3,1796.9,249.4,7278717,...,60.3,193,13.6,82.5992,37.7,35.5,38.1,0.167072,0.172756,0.16136
5,ARKANSAS,584.6,447.8,8,51.6,2858,599.6,2012.6,245.9,3017804,...,60.4,123,50.6,84.5835,38.1,36.3,39,0.161854,0.166034,0.157748
6,CALIFORNIA,441.2,267.1,4.3,132.4,2331.2,386.1,1586.3,358.8,39512223,...,59.4,146,22.2,87.1416,36.5,34.6,37,0.164324,0.168907,0.1597
7,COLORADO,381,246.3,3.8,63.6,2590.7,348.4,1858.3,384,5758736,...,45.1,136,15.9,82.0307,36.7,35.5,37.5,0.15041,0.154748,0.145948

In [693]:
#View summary of data frame information after cleaning 
crimestats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 3 to 50
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         48 non-null     object
 1   Violent       48 non-null     object
 2   Assault       48 non-null     object
 3   Murder        48 non-null     object
 4   Robbery       48 non-null     object
 5   PropCrime     48 non-null     object
 6   Burglary      48 non-null     object
 7   Larceny       48 non-null     object
 8   CarTheft      48 non-null     object
 9   Population    48 non-null     object
 10  PerCapIncome  48 non-null     object
 11  %Metro        48 non-null     object
 12  %Bachelors+   48 non-null     object
 13  %Unemploy     48 non-null     object
 14  %Poverty      48 non-null     object
 15  Temp          48 non-null     object
 16  Sun           48 non-null     object
 17  Rain          48 non-null     object
 18  %SameHouse    48 non-null     object
 19  MedianAge     48 non-null     object
 20  MedAgeMale    48 non-null     object
 21  MedAgeFemale  48 non-null     object
 22  %young        48 non-null     object
 23  %youngmale    48 non-null     object
 24  %youngfemale  48 non-null     object
dtypes: object(25)
memory usage: 9.8+ KB

# Run Multiple Linear Regressions

In [694]:
#Model A: Robbery = f(%Metro, %Poverty, Rain)
#Model B: Robbery = f(Population, %SameHouse, MedianAge)
#Model C: Robbery = f(Population, %SameHouse, MedAgeMale)
#Model D: Robbery = f(Population, %SameHouse, MedAgeFemale)
#Model E: Robbery = f(CarTheft, %Unemploy, %Bachelors+, Temp)
#Model F: Robbery = f(CarTheft, %Unemploy, %Bachelors+, Sun)
#Model G: Robbery = f(CarTheft, %Unemploy, %Bachelors+, Rain)

In [704]:
#Define Dependent and Idependent Variables
y = crimestats["Robbery"]
x1A = crimestats[["%Metro", "%Poverty", "Rain"]]
x1B = crimestats[["Population", "%SameHouse", "MedianAge"]]
x1C = crimestats[["Population", "%SameHouse", "MedAgeMale"]]
x1D = crimestats[["Population", "%SameHouse", "MedAgeFemale"]]
x1E = crimestats[["CarTheft", "%Unemploy", "%Bachelors+", "Temp"]]
x1F = crimestats[["CarTheft", "%Unemploy", "%Bachelors+", "Sun"]]
x1G = crimestats[["CarTheft", "%Unemploy", "%Bachelors+", "Rain"]]

In [705]:
#Generate the constants for the y-intercept 
xA = sm.add_constant(x1A)
xB = sm.add_constant(x1B)
xC = sm.add_constant(x1C)
xD = sm.add_constant(x1D)
xE = sm.add_constant(x1E)
xF = sm.add_constant(x1F)
xG = sm.add_constant(x1G)

In [710]:
#Model A Regression 
#Since the variables in the data frame are object types instead of numeric types you can set the parameters of the regression to float
results = sm.OLS(y.astype(float),xA.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.537
Model:                            OLS   Adj. R-squared:                  0.505
Method:                 Least Squares   F-statistic:                     16.99
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           1.79e-07
Time:                        00:13:35   Log-Likelihood:                -215.57
No. Observations:                  48   AIC:                             439.1
Df Residuals:                      44   BIC:                             446.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -84.9664     22.641     -3.753      0.001    -130.597     -39.336
%Metro       128.6981     19.206      6.701      0.000      89.991     167.405
%Poverty       4.8139      1.349      3.568      0.001       2.095       7.533
Rain          -0.3085      0.253     -1.221      0.229      -0.818       0.201
==============================================================================
Omnibus:                       13.282   Durbin-Watson:                   2.409
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               24.171
Skew:                           0.712   Prob(JB):                     5.64e-06
Kurtosis:                       6.172   Cond. No.                         348.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [752]:
#Model B Regression
results = sm.OLS(y.astype(float),xB.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.365
Model:                            OLS   Adj. R-squared:                  0.322
Method:                 Least Squares   F-statistic:                     8.426
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           0.000155
Time:                        00:34:15   Log-Likelihood:                -223.14
No. Observations:                  48   AIC:                             454.3
Df Residuals:                      44   BIC:                             461.8
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -125.1410    174.711     -0.716      0.478    -477.248     226.966
Population  2.169e-06   5.48e-07      3.956      0.000    1.06e-06    3.27e-06
%SameHouse     3.2982      2.399      1.375      0.176      -1.537       8.133
MedianAge     -2.8525      1.988     -1.435      0.158      -6.859       1.154
==============================================================================
Omnibus:                       17.352   Durbin-Watson:                   2.377
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.071
Skew:                           1.269   Prob(JB):                     1.61e-05
Kurtosis:                       5.143   Cond. No.                     4.59e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.59e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [753]:
#Model C Regression
results = sm.OLS(y.astype(float),xC.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.383
Model:                            OLS   Adj. R-squared:                  0.341
Method:                 Least Squares   F-statistic:                     9.091
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           8.48e-05
Time:                        00:34:27   Log-Likelihood:                -222.46
No. Observations:                  48   AIC:                             452.9
Df Residuals:                      44   BIC:                             460.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -106.5479    169.824     -0.627      0.534    -448.806     235.710
Population  2.113e-06    5.4e-07      3.912      0.000    1.02e-06     3.2e-06
%SameHouse     3.3465      2.243      1.492      0.143      -1.175       7.868
MedAgeMale    -3.5997      1.956     -1.840      0.073      -7.543       0.343
==============================================================================
Omnibus:                       17.592   Durbin-Watson:                   2.344
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.980
Skew:                           1.261   Prob(JB):                     1.02e-05
Kurtosis:                       5.265   Cond. No.                     4.53e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.53e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [754]:
#Model D Regression
results = sm.OLS(y.astype(float),xD.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.362
Model:                            OLS   Adj. R-squared:                  0.318
Method:                 Least Squares   F-statistic:                     8.315
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           0.000172
Time:                        00:35:52   Log-Likelihood:                -223.26
No. Observations:                  48   AIC:                             454.5
Df Residuals:                      44   BIC:                             462.0
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         -130.2178    176.294     -0.739      0.464    -485.514     225.079
Population    2.188e-06   5.48e-07      3.990      0.000    1.08e-06    3.29e-06
%SameHouse       3.2588      2.429      1.342      0.187      -1.637       8.154
MedAgeFemale    -2.5855      1.908     -1.355      0.182      -6.430       1.259
==============================================================================
Omnibus:                       16.864   Durbin-Watson:                   2.376
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               21.403
Skew:                           1.228   Prob(JB):                     2.25e-05
Kurtosis:                       5.161   Cond. No.                     4.62e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.62e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [755]:
#Model E Regression
results = sm.OLS(y.astype(float),xE.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.572
Model:                            OLS   Adj. R-squared:                  0.533
Method:                 Least Squares   F-statistic:                     14.39
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           1.55e-07
Time:                        00:36:08   Log-Likelihood:                -213.65
No. Observations:                  48   AIC:                             437.3
Df Residuals:                      43   BIC:                             446.6
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        -204.8832     41.074     -4.988      0.000    -287.716    -122.051
CarTheft        0.1146      0.037      3.118      0.003       0.040       0.189
%Unemploy      17.3684      4.946      3.511      0.001       7.393      27.344
%Bachelors+   263.5344     67.393      3.910      0.000     127.623     399.446
Temp            1.8498      0.480      3.850      0.000       0.881       2.819
==============================================================================
Omnibus:                        9.141   Durbin-Watson:                   2.054
Prob(Omnibus):                  0.010   Jarque-Bera (JB):                8.343
Skew:                           0.932   Prob(JB):                       0.0154
Kurtosis:                       3.836   Cond. No.                     5.58e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [756]:
#Model F Regression
results = sm.OLS(y.astype(float),xF.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.444
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     8.571
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           3.54e-05
Time:                        00:36:45   Log-Likelihood:                -219.97
No. Observations:                  48   AIC:                             449.9
Df Residuals:                      43   BIC:                             459.3
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        -128.5383     40.339     -3.186      0.003    -209.889     -47.187
CarTheft        0.1245      0.047      2.677      0.010       0.031       0.218
%Unemploy      21.5975      5.510      3.920      0.000      10.485      32.710
%Bachelors+   212.9705     75.193      2.832      0.007      61.329     364.612
Sun             0.1852      0.155      1.197      0.238      -0.127       0.497
==============================================================================
Omnibus:                        5.412   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.067   Jarque-Bera (JB):                4.294
Skew:                           0.686   Prob(JB):                        0.117
Kurtosis:                       3.516   Cond. No.                     5.72e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [757]:
#Model G Regression
results = sm.OLS(y.astype(float),xG.astype(float)).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Robbery   R-squared:                       0.494
Model:                            OLS   Adj. R-squared:                  0.447
Method:                 Least Squares   F-statistic:                     10.51
Date:                Wed, 22 Dec 2021   Prob (F-statistic):           4.99e-06
Time:                        00:37:10   Log-Likelihood:                -217.67
No. Observations:                  48   AIC:                             445.3
Df Residuals:                      43   BIC:                             454.7
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        -142.2632     38.255     -3.719      0.001    -219.413     -65.114
CarTheft        0.1883      0.041      4.557      0.000       0.105       0.272
%Unemploy      19.6788      5.304      3.710      0.001       8.981      30.376
%Bachelors+   222.6544     71.795      3.101      0.003      77.866     367.443
Rain            0.6385      0.263      2.428      0.019       0.108       1.169
==============================================================================
Omnibus:                        5.096   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                3.915
Skew:                           0.620   Prob(JB):                        0.141
Kurtosis:                       3.649   Cond. No.                     5.28e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.28e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""